"""Validated, chunked sensor-series primitives for materials research."""

from ultra_deepagents.sensors.model import (
    EnvelopeBucket,
    LineageBinding,
    MinMaxEnvelope,
    SensorSeries,
    SpecimenRecord,
    TreeManifestVerification,
)
from ultra_deepagents.sensors.reader import (
    CANONICAL_JSON_SCHEMA,
    DEFAULT_VALIDATION_MAX_DECODED_BYTES,
    DEFAULT_VALIDATION_MAX_READS,
    DEFAULT_VALIDATION_MAX_VALUES,
    DEFAULT_VALIDATION_MAX_WALL_SECONDS,
    SENSOR_SCHEMA,
    TREE_MANIFEST_SCHEMA,
    SensorValidationBudget,
    SensorValidationError,
    build_min_max_envelope,
    canonical_json_bytes,
    canonical_sha256,
    open_sensor_series,
    parse_sensor_series,
    verify_tree_manifest,
)

__all__ = [
    "CANONICAL_JSON_SCHEMA",
    "DEFAULT_VALIDATION_MAX_DECODED_BYTES",
    "DEFAULT_VALIDATION_MAX_READS",
    "DEFAULT_VALIDATION_MAX_VALUES",
    "DEFAULT_VALIDATION_MAX_WALL_SECONDS",
    "SENSOR_SCHEMA",
    "TREE_MANIFEST_SCHEMA",
    "EnvelopeBucket",
    "LineageBinding",
    "MinMaxEnvelope",
    "SensorSeries",
    "SpecimenRecord",
    "SensorValidationBudget",
    "SensorValidationError",
    "TreeManifestVerification",
    "build_min_max_envelope",
    "canonical_json_bytes",
    "canonical_sha256",
    "open_sensor_series",
    "parse_sensor_series",
    "verify_tree_manifest",
]
