// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlArtifact struct {
	ArtifactID    string             `json:"artifact_id"`
	RunID         string             `json:"run_id"`
	ThreadID      pgtype.Text        `json:"thread_id"`
	Kind          string             `json:"kind"`
	Path          pgtype.Text        `json:"path"`
	SourcePath    pgtype.Text        `json:"source_path"`
	PreviewPath   pgtype.Text        `json:"preview_path"`
	Title         pgtype.Text        `json:"title"`
	ResultGroupID pgtype.Text        `json:"result_group_id"`
	MimeType      pgtype.Text        `json:"mime_type"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	Sha256        pgtype.Text        `json:"sha256"`
	StorageUri    pgtype.Text        `json:"storage_uri"`
	ToolName      pgtype.Text        `json:"tool_name"`
	Category      pgtype.Text        `json:"category"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Metadata      []byte             `json:"metadata"`
}

type ControlBisqueCredential struct {
	SessionID          string             `json:"session_id"`
	UserID             string             `json:"user_id"`
	OrgID              pgtype.Text        `json:"org_id"`
	RootUrl            string             `json:"root_url"`
	Username           string             `json:"username"`
	PasswordCiphertext string             `json:"password_ciphertext"`
	PasswordNonce      string             `json:"password_nonce"`
	PasswordKeyID      string             `json:"password_key_id"`
	PasswordAlgorithm  string             `json:"password_algorithm"`
	Status             string             `json:"status"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlCalphadEvidenceBlob struct {
	EvidenceSha256    string             `json:"evidence_sha256"`
	EvidenceSizeBytes int64              `json:"evidence_size_bytes"`
	Encoding          string             `json:"encoding"`
	Payload           []byte             `json:"payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ControlCalphadInputBlob struct {
	InputSha256    string             `json:"input_sha256"`
	InputSizeBytes int64              `json:"input_size_bytes"`
	Encoding       string             `json:"encoding"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ControlCalphadRevision struct {
	RevisionID              string             `json:"revision_id"`
	ResourceID              string             `json:"resource_id"`
	OwnerUserID             string             `json:"owner_user_id"`
	OwnerOrgID              pgtype.Text        `json:"owner_org_id"`
	Sha256                  string             `json:"sha256"`
	SizeBytes               int64              `json:"size_bytes"`
	DatabaseFormat          string             `json:"database_format"`
	AssessmentPressureMinPa pgtype.Float8      `json:"assessment_pressure_min_pa"`
	AssessmentPressureMaxPa pgtype.Float8      `json:"assessment_pressure_max_pa"`
	ParentRevisionID        pgtype.Text        `json:"parent_revision_id"`
	CreatedByUserID         pgtype.Text        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	Metadata                []byte             `json:"metadata"`
}

type ControlCalphadTenantCapacity struct {
	OwnerUserID           string             `json:"owner_user_id"`
	OwnerOrgID            string             `json:"owner_org_id"`
	MaxRetainedBytes      int64              `json:"max_retained_bytes"`
	MaxValidationEvents   int64              `json:"max_validation_events"`
	RetainedInputBytes    int64              `json:"retained_input_bytes"`
	RetainedEvidenceBytes int64              `json:"retained_evidence_bytes"`
	ValidationEvents      int64              `json:"validation_events"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ControlCalphadValidationEvent struct {
	ValidationID             string             `json:"validation_id"`
	RevisionID               string             `json:"revision_id"`
	ResourceID               string             `json:"resource_id"`
	DatabaseSha256           string             `json:"database_sha256"`
	DatabaseSizeBytes        int64              `json:"database_size_bytes"`
	DatabaseFormat           string             `json:"database_format"`
	AssessmentPressureMinPa  pgtype.Float8      `json:"assessment_pressure_min_pa"`
	AssessmentPressureMaxPa  pgtype.Float8      `json:"assessment_pressure_max_pa"`
	DatabaseInventorySha256  pgtype.Text        `json:"database_inventory_sha256"`
	RequestSha256            pgtype.Text        `json:"request_sha256"`
	Status                   string             `json:"status"`
	Operation                string             `json:"operation"`
	FailureDomain            pgtype.Text        `json:"failure_domain"`
	FailureStage             pgtype.Text        `json:"failure_stage"`
	FailureCode              pgtype.Text        `json:"failure_code"`
	EvidencePath             pgtype.Text        `json:"evidence_path"`
	EvidenceSha256           pgtype.Text        `json:"evidence_sha256"`
	EvidenceSizeBytes        pgtype.Int8        `json:"evidence_size_bytes"`
	RuntimeImageID           pgtype.Text        `json:"runtime_image_id"`
	PycalphadVersion         pgtype.Text        `json:"pycalphad_version"`
	RunID                    pgtype.Text        `json:"run_id"`
	InspectionEvidenceSha256 pgtype.Text        `json:"inspection_evidence_sha256"`
	EvidenceContractVersion  pgtype.Text        `json:"evidence_contract_version"`
	CreatedByAuthority       string             `json:"created_by_authority"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	Metadata                 []byte             `json:"metadata"`
}

type ControlDataAgentJob struct {
	JobID             string             `json:"job_id"`
	OwnerUserID       string             `json:"owner_user_id"`
	OwnerOrgID        pgtype.Text        `json:"owner_org_id"`
	OwnerRole         pgtype.Text        `json:"owner_role"`
	ProjectID         pgtype.Text        `json:"project_id"`
	JobType           string             `json:"job_type"`
	Status            string             `json:"status"`
	ResourceCount     int64              `json:"resource_count"`
	ProgressCompleted int64              `json:"progress_completed"`
	ProgressTotal     int64              `json:"progress_total"`
	Error             pgtype.Text        `json:"error"`
	CreatedByUserID   pgtype.Text        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	InputSelector     []byte             `json:"input_selector"`
	OutputSummary     []byte             `json:"output_summary"`
	Metadata          []byte             `json:"metadata"`
}

type ControlDataAgentJobEvent struct {
	EventID     string             `json:"event_id"`
	JobID       string             `json:"job_id"`
	Sequence    int64              `json:"sequence"`
	EventType   string             `json:"event_type"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Message     pgtype.Text        `json:"message"`
	Metadata    []byte             `json:"metadata"`
}

type ControlDataAgentJobLease struct {
	JobID          string             `json:"job_id"`
	WorkerID       string             `json:"worker_id"`
	LeaseToken     string             `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlDataAgentJobResource struct {
	JobID      string `json:"job_id"`
	ResourceID string `json:"resource_id"`
	Position   int64  `json:"position"`
	Metadata   []byte `json:"metadata"`
	IoRole     string `json:"io_role"`
}

type ControlDatasetSnapshot struct {
	SnapshotID         string             `json:"snapshot_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	ProjectID          pgtype.Text        `json:"project_id"`
	SourceCollectionID pgtype.Text        `json:"source_collection_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Status             string             `json:"status"`
	ResourceCount      int64              `json:"resource_count"`
	TotalBytes         int64              `json:"total_bytes"`
	CreatedByUserID    pgtype.Text        `json:"created_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlDatasetSnapshotEvent struct {
	EventID     string             `json:"event_id"`
	SnapshotID  string             `json:"snapshot_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

type ControlDatasetSnapshotResource struct {
	SnapshotID        string             `json:"snapshot_id"`
	ResourceID        string             `json:"resource_id"`
	Position          int64              `json:"position"`
	OriginalName      string             `json:"original_name"`
	ContentType       pgtype.Text        `json:"content_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Sha256            pgtype.Text        `json:"sha256"`
	SourceType        string             `json:"source_type"`
	ResourceKind      string             `json:"resource_kind"`
	StorageUri        pgtype.Text        `json:"storage_uri"`
	SourceUri         pgtype.Text        `json:"source_uri"`
	ProjectID         pgtype.Text        `json:"project_id"`
	ResourceCreatedAt pgtype.Timestamptz `json:"resource_created_at"`
	Metadata          []byte             `json:"metadata"`
}

type ControlDatasetSnapshotShareGrant struct {
	GrantID         string             `json:"grant_id"`
	SnapshotID      string             `json:"snapshot_id"`
	OwnerUserID     string             `json:"owner_user_id"`
	OwnerOrgID      pgtype.Text        `json:"owner_org_id"`
	OwnerRole       pgtype.Text        `json:"owner_role"`
	GranteeUserID   pgtype.Text        `json:"grantee_user_id"`
	GranteeOrgID    pgtype.Text        `json:"grantee_org_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.Text        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlOrganization struct {
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Metadata  []byte             `json:"metadata"`
}

type ControlResource struct {
	ResourceID         string             `json:"resource_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	OriginalName       string             `json:"original_name"`
	ContentType        pgtype.Text        `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             pgtype.Text        `json:"sha256"`
	StorageUri         pgtype.Text        `json:"storage_uri"`
	StoragePath        pgtype.Text        `json:"storage_path"`
	SourceType         string             `json:"source_type"`
	ResourceKind       string             `json:"resource_kind"`
	SourceUri          pgtype.Text        `json:"source_uri"`
	ProjectID          pgtype.Text        `json:"project_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	RetentionExpiresAt pgtype.Timestamptz `json:"retention_expires_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlResourceCollection struct {
	CollectionID       string             `json:"collection_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	ProjectID          pgtype.Text        `json:"project_id"`
	ParentCollectionID pgtype.Text        `json:"parent_collection_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	CollectionType     string             `json:"collection_type"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlResourceCollectionMember struct {
	CollectionID  string             `json:"collection_id"`
	ResourceID    string             `json:"resource_id"`
	Position      int64              `json:"position"`
	AddedByUserID pgtype.Text        `json:"added_by_user_id"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
	Metadata      []byte             `json:"metadata"`
}

type ControlResourceCollectionShareGrant struct {
	GrantID         string             `json:"grant_id"`
	CollectionID    string             `json:"collection_id"`
	OwnerUserID     string             `json:"owner_user_id"`
	OwnerOrgID      pgtype.Text        `json:"owner_org_id"`
	OwnerRole       pgtype.Text        `json:"owner_role"`
	GranteeUserID   pgtype.Text        `json:"grantee_user_id"`
	GranteeOrgID    pgtype.Text        `json:"grantee_org_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.Text        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlResourceEvent struct {
	EventID     string             `json:"event_id"`
	ResourceID  string             `json:"resource_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

type ControlResourceSearchDocument struct {
	ResourceID   string             `json:"resource_id"`
	OwnerUserID  string             `json:"owner_user_id"`
	OwnerOrgID   pgtype.Text        `json:"owner_org_id"`
	ProjectID    pgtype.Text        `json:"project_id"`
	Status       string             `json:"status"`
	SearchText   string             `json:"search_text"`
	SearchVector interface{}        `json:"search_vector"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ControlResourceSearchFact struct {
	ResourceID  string             `json:"resource_id"`
	OwnerUserID string             `json:"owner_user_id"`
	OwnerOrgID  pgtype.Text        `json:"owner_org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	Status      string             `json:"status"`
	FactKey     string             `json:"fact_key"`
	FactText    string             `json:"fact_text"`
	FactNumber  pgtype.Float8      `json:"fact_number"`
	FactSource  string             `json:"fact_source"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ControlResourceShareGrant struct {
	GrantID         string             `json:"grant_id"`
	ResourceID      string             `json:"resource_id"`
	OwnerUserID     string             `json:"owner_user_id"`
	OwnerOrgID      pgtype.Text        `json:"owner_org_id"`
	OwnerRole       pgtype.Text        `json:"owner_role"`
	GranteeUserID   pgtype.Text        `json:"grantee_user_id"`
	GranteeOrgID    pgtype.Text        `json:"grantee_org_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.Text        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlRun struct {
	RunID           string             `json:"run_id"`
	ThreadID        string             `json:"thread_id"`
	UserID          string             `json:"user_id"`
	Goal            string             `json:"goal"`
	Status          string             `json:"status"`
	WorkflowKind    string             `json:"workflow_kind"`
	Mode            pgtype.Text        `json:"mode"`
	CurrentNode     pgtype.Text        `json:"current_node"`
	ParentRunID     pgtype.Text        `json:"parent_run_id"`
	PlannerVersion  pgtype.Text        `json:"planner_version"`
	AgentRole       pgtype.Text        `json:"agent_role"`
	TraceGroupID    pgtype.Text        `json:"trace_group_id"`
	CheckpointID    pgtype.Text        `json:"checkpoint_id"`
	CheckpointState []byte             `json:"checkpoint_state"`
	BudgetState     []byte             `json:"budget_state"`
	ResponseText    pgtype.Text        `json:"response_text"`
	Error           pgtype.Text        `json:"error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlRunEvent struct {
	EventID        string             `json:"event_id"`
	SequenceNumber int64              `json:"sequence_number"`
	SourceSequence pgtype.Int8        `json:"source_sequence"`
	RunID          string             `json:"run_id"`
	ThreadID       pgtype.Text        `json:"thread_id"`
	EventKind      string             `json:"event_kind"`
	EventType      pgtype.Text        `json:"event_type"`
	NodeName       pgtype.Text        `json:"node_name"`
	TaskID         pgtype.Text        `json:"task_id"`
	CheckpointID   pgtype.Text        `json:"checkpoint_id"`
	ScopeID        pgtype.Text        `json:"scope_id"`
	AgentRole      pgtype.Text        `json:"agent_role"`
	Level          pgtype.Text        `json:"level"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Message        pgtype.Text        `json:"message"`
	Payload        []byte             `json:"payload"`
}

type ControlRunEventSequence struct {
	RunID        string `json:"run_id"`
	LastSequence int64  `json:"last_sequence"`
}

type ControlRunLease struct {
	RunID          string             `json:"run_id"`
	WorkerID       string             `json:"worker_id"`
	LeaseToken     string             `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlRunTokenUsage struct {
	RunID        string             `json:"run_id"`
	UsageEventID string             `json:"usage_event_id"`
	UserID       string             `json:"user_id"`
	Model        string             `json:"model"`
	Day          pgtype.Date        `json:"day"`
	InputTokens  int64              `json:"input_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ControlRunTokenUsageFinalized struct {
	RunID       string             `json:"run_id"`
	UserID      string             `json:"user_id"`
	Day         pgtype.Date        `json:"day"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
}

type ControlThread struct {
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LatestRunID  pgtype.Text        `json:"latest_run_id"`
	CheckpointID pgtype.Text        `json:"checkpoint_id"`
	Summary      pgtype.Text        `json:"summary"`
	Metadata     []byte             `json:"metadata"`
}

type ControlThreadMessage struct {
	MessageID string             `json:"message_id"`
	ThreadID  string             `json:"thread_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	RunID     pgtype.Text        `json:"run_id"`
}

type ControlTrainingBenchmarkRun struct {
	RunID              string             `json:"run_id"`
	ModelVersionID     string             `json:"model_version_id"`
	GoldSetID          string             `json:"gold_set_id"`
	GoldSetContentHash string             `json:"gold_set_content_hash"`
	MetricSchema       string             `json:"metric_schema"`
	KernelVersion      string             `json:"kernel_version"`
	Metrics            []byte             `json:"metrics"`
	GuardrailsPassed   bool               `json:"guardrails_passed"`
	GuardrailsReasons  []byte             `json:"guardrails_reasons"`
	ReportUri          string             `json:"report_uri"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ControlTrainingCanaryObservation struct {
	ObservationID   string             `json:"observation_id"`
	ModelKey        pgtype.Text        `json:"model_key"`
	CanaryVersionID string             `json:"canary_version_id"`
	ActiveVersionID string             `json:"active_version_id"`
	RunID           string             `json:"run_id"`
	CanaryMetrics   []byte             `json:"canary_metrics"`
	ActiveMetrics   []byte             `json:"active_metrics"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ControlTrainingDomain struct {
	DomainID    string             `json:"domain_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ControlTrainingGateConfigEvent struct {
	EventID     string             `json:"event_id"`
	ModelKey    string             `json:"model_key"`
	TableName   string             `json:"table_name"`
	Change      []byte             `json:"change"`
	ActorUserID string             `json:"actor_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ControlTrainingGatePolicy struct {
	ModelKey           string `json:"model_key"`
	MinReviewed        int64  `json:"min_reviewed"`
	MinNewObjects      int64  `json:"min_new_objects"`
	MinPerClassObjects []byte `json:"min_per_class_objects"`
	MinDays            int64  `json:"min_days"`
}

type ControlTrainingGoldItem struct {
	GoldSetID     string      `json:"gold_set_id"`
	ItemID        string      `json:"item_id"`
	SourceRef     []byte      `json:"source_ref"`
	Slice         string      `json:"slice"`
	LabelKind     string      `json:"label_kind"`
	ContentSha256 string      `json:"content_sha256"`
	Phash         pgtype.Text `json:"phash"`
	GtLabelSha256 string      `json:"gt_label_sha256"`
	GtLabelUri    string      `json:"gt_label_uri"`
	Width         pgtype.Int8 `json:"width"`
	Height        pgtype.Int8 `json:"height"`
	Metadata      []byte      `json:"metadata"`
	FootprintGeom []byte      `json:"footprint_geom"`
	StrataTags    []byte      `json:"strata_tags"`
}

type ControlTrainingGoldSet struct {
	GoldSetID        string             `json:"gold_set_id"`
	ModelKey         string             `json:"model_key"`
	Version          int64              `json:"version"`
	ContentHash      pgtype.Text        `json:"content_hash"`
	ItemCount        int64              `json:"item_count"`
	LabelStats       []byte             `json:"label_stats"`
	StrataSummary    []byte             `json:"strata_summary"`
	SplitManifestUri pgtype.Text        `json:"split_manifest_uri"`
	Provenance       []byte             `json:"provenance"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedByUserID  string             `json:"created_by_user_id"`
	FrozenAt         pgtype.Timestamptz `json:"frozen_at"`
}

type ControlTrainingGuardrailClause struct {
	ModelKey   string      `json:"model_key"`
	ClauseKey  string      `json:"clause_key"`
	MetricPath string      `json:"metric_path"`
	Comparator string      `json:"comparator"`
	Value      float32     `json:"value"`
	Slice      pgtype.Text `json:"slice"`
	Params     []byte      `json:"params"`
	Enabled    bool        `json:"enabled"`
	Required   bool        `json:"required"`
}

type ControlTrainingJob struct {
	JobID             string             `json:"job_id"`
	ModelKey          string             `json:"model_key"`
	JobType           string             `json:"job_type"`
	Status            string             `json:"status"`
	GpuPool           pgtype.Text        `json:"gpu_pool"`
	Params            []byte             `json:"params"`
	ProgressCompleted int64              `json:"progress_completed"`
	ProgressTotal     int64              `json:"progress_total"`
	Error             pgtype.Text        `json:"error"`
	OwnerUserID       string             `json:"owner_user_id"`
	OwnerOrgID        pgtype.Text        `json:"owner_org_id"`
	CreatedByUserID   pgtype.Text        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	OutputSummary     []byte             `json:"output_summary"`
	Metadata          []byte             `json:"metadata"`
}

type ControlTrainingJobEvent struct {
	EventID     string             `json:"event_id"`
	JobID       string             `json:"job_id"`
	Sequence    int64              `json:"sequence"`
	EventType   string             `json:"event_type"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Message     pgtype.Text        `json:"message"`
	Metadata    []byte             `json:"metadata"`
}

type ControlTrainingJobLease struct {
	JobID          string             `json:"job_id"`
	WorkerID       string             `json:"worker_id"`
	LeaseToken     string             `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlTrainingLineage struct {
	LineageID       string             `json:"lineage_id"`
	DomainID        string             `json:"domain_id"`
	ModelKey        string             `json:"model_key"`
	Scope           string             `json:"scope"`
	OwnerUserID     pgtype.Text        `json:"owner_user_id"`
	ParentLineageID pgtype.Text        `json:"parent_lineage_id"`
	ActiveVersionID pgtype.Text        `json:"active_version_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ControlTrainingModel struct {
	ModelKey             string             `json:"model_key"`
	TaskType             string             `json:"task_type"`
	DisplayName          string             `json:"display_name"`
	DatasetFormat        string             `json:"dataset_format"`
	MetricSchema         string             `json:"metric_schema"`
	RequiresPhash        bool               `json:"requires_phash"`
	Capabilities         []byte             `json:"capabilities"`
	Executor             []byte             `json:"executor"`
	Classes              []byte             `json:"classes"`
	LeakageDefensesExtra []byte             `json:"leakage_defenses_extra"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ControlTrainingModelStatus struct {
	ModelKey               string             `json:"model_key"`
	DatasetName            pgtype.Text        `json:"dataset_name"`
	DatasetID              pgtype.Text        `json:"dataset_id"`
	ModelHealth            pgtype.Text        `json:"model_health"`
	ReviewedImages         int64              `json:"reviewed_images"`
	UnreviewedImages       int64              `json:"unreviewed_images"`
	ClassCounts            []byte             `json:"class_counts"`
	PerClassNewObjects     []byte             `json:"per_class_new_objects"`
	UnsupportedClassCounts []byte             `json:"unsupported_class_counts"`
	LastSyncAt             pgtype.Timestamptz `json:"last_sync_at"`
	LastRetrainAt          pgtype.Timestamptz `json:"last_retrain_at"`
	ActiveModelVersion     pgtype.Text        `json:"active_model_version"`
	RetrainGate            bool               `json:"retrain_gate"`
	RetrainGateReasons     []byte             `json:"retrain_gate_reasons"`
	RetrainGateCounts      []byte             `json:"retrain_gate_counts"`
	RetrainGateThresholds  []byte             `json:"retrain_gate_thresholds"`
}

type ControlTrainingModelVersion struct {
	VersionID     string             `json:"version_id"`
	LineageID     string             `json:"lineage_id"`
	ModelKey      string             `json:"model_key"`
	Status        string             `json:"status"`
	IsFrozen      bool               `json:"is_frozen"`
	WeightsUri    pgtype.Text        `json:"weights_uri"`
	SourceJobID   pgtype.Text        `json:"source_job_id"`
	ArtifactRunID pgtype.Text        `json:"artifact_run_id"`
	Metrics       []byte             `json:"metrics"`
	Metadata      []byte             `json:"metadata"`
	ActivatedAt   pgtype.Timestamptz `json:"activated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ControlTrainingModelVersionEvent struct {
	EventID            string             `json:"event_id"`
	VersionID          string             `json:"version_id"`
	EventType          string             `json:"event_type"`
	ActorUserID        string             `json:"actor_user_id"`
	FromStatus         pgtype.Text        `json:"from_status"`
	ToStatus           pgtype.Text        `json:"to_status"`
	BenchmarkRunID     pgtype.Text        `json:"benchmark_run_id"`
	GoldSetContentHash pgtype.Text        `json:"gold_set_content_hash"`
	Reason             pgtype.Text        `json:"reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ControlTrainingReplayPool struct {
	ModelKey       string        `json:"model_key"`
	ContentSha256  string        `json:"content_sha256"`
	SourceRef      []byte        `json:"source_ref"`
	LabelStats     []byte        `json:"label_stats"`
	SiteID         pgtype.Text   `json:"site_id"`
	ForgettingRisk pgtype.Float4 `json:"forgetting_risk"`
	LastUsedEpoch  pgtype.Int8   `json:"last_used_epoch"`
	Priority       pgtype.Float4 `json:"priority"`
}

type ControlTrainingRetrainRequest struct {
	RequestID                 string             `json:"request_id"`
	ModelKey                  string             `json:"model_key"`
	TrainingJobID             pgtype.Text        `json:"training_job_id"`
	Status                    string             `json:"status"`
	Note                      pgtype.Text        `json:"note"`
	Error                     pgtype.Text        `json:"error"`
	ModelVersion              pgtype.Text        `json:"model_version"`
	GatingSummary             []byte             `json:"gating_summary"`
	BenchmarkReportArtifactID pgtype.Text        `json:"benchmark_report_artifact_id"`
	RequestedByUserID         pgtype.Text        `json:"requested_by_user_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	FinishedAt                pgtype.Timestamptz `json:"finished_at"`
}

type ControlUploadChunk struct {
	SessionID  string             `json:"session_id"`
	FileToken  string             `json:"file_token"`
	ChunkIndex int32              `json:"chunk_index"`
	ByteOffset int64              `json:"byte_offset"`
	SizeBytes  int64              `json:"size_bytes"`
	Sha256     string             `json:"sha256"`
	Status     string             `json:"status"`
	StorageUri pgtype.Text        `json:"storage_uri"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	Error      pgtype.Text        `json:"error"`
	Metadata   []byte             `json:"metadata"`
}

type ControlUploadSession struct {
	SessionID          string             `json:"session_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	ProjectID          pgtype.Text        `json:"project_id"`
	SourceType         string             `json:"source_type"`
	Status             string             `json:"status"`
	TotalBytes         int64              `json:"total_bytes"`
	BytesReceived      int64              `json:"bytes_received"`
	BytesVerified      int64              `json:"bytes_verified"`
	BytesCommitted     int64              `json:"bytes_committed"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	BrowserFingerprint pgtype.Text        `json:"browser_fingerprint"`
	Error              pgtype.Text        `json:"error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlUploadSessionEvent struct {
	EventID     string             `json:"event_id"`
	SessionID   string             `json:"session_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

type ControlUploadSessionFile struct {
	SessionID      string             `json:"session_id"`
	FileToken      string             `json:"file_token"`
	ResourceID     pgtype.Text        `json:"resource_id"`
	OriginalName   string             `json:"original_name"`
	RelativePath   pgtype.Text        `json:"relative_path"`
	ContentType    pgtype.Text        `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	DeclaredSha256 pgtype.Text        `json:"declared_sha256"`
	ComputedSha256 pgtype.Text        `json:"computed_sha256"`
	Status         string             `json:"status"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Metadata       []byte             `json:"metadata"`
}

type ControlUser struct {
	UserID      string             `json:"user_id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	OrgID       pgtype.Text        `json:"org_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Metadata    []byte             `json:"metadata"`
}

type ControlUserTokenUsageDaily struct {
	UserID       string             `json:"user_id"`
	Day          pgtype.Date        `json:"day"`
	InputTokens  int64              `json:"input_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	RunCount     int64              `json:"run_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ControlUserTokenUsageLifetime struct {
	UserID         string             `json:"user_id"`
	InputTokens    int64              `json:"input_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	TotalTokens    int64              `json:"total_tokens"`
	PeakDailyTotal int64              `json:"peak_daily_total"`
	LastActiveDay  pgtype.Date        `json:"last_active_day"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlWorkerHeartbeat struct {
	WorkerID        string             `json:"worker_id"`
	WorkerKind      string             `json:"worker_kind"`
	Status          string             `json:"status"`
	CurrentRunID    pgtype.Text        `json:"current_run_id"`
	Hostname        pgtype.Text        `json:"hostname"`
	Version         pgtype.Text        `json:"version"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Metadata        []byte             `json:"metadata"`
}
