// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlArtifact struct {
	ArtifactID    string             `json:"artifact_id"`
	RunID         string             `json:"run_id"`
	ThreadID      pgtype.Text        `json:"thread_id"`
	Kind          string             `json:"kind"`
	Path          pgtype.Text        `json:"path"`
	SourcePath    pgtype.Text        `json:"source_path"`
	PreviewPath   pgtype.Text        `json:"preview_path"`
	Title         pgtype.Text        `json:"title"`
	ResultGroupID pgtype.Text        `json:"result_group_id"`
	MimeType      pgtype.Text        `json:"mime_type"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	Sha256        pgtype.Text        `json:"sha256"`
	StorageUri    pgtype.Text        `json:"storage_uri"`
	ToolName      pgtype.Text        `json:"tool_name"`
	Category      pgtype.Text        `json:"category"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Metadata      []byte             `json:"metadata"`
}

type ControlOrganization struct {
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Metadata  []byte             `json:"metadata"`
}

type ControlRun struct {
	RunID           string             `json:"run_id"`
	ThreadID        string             `json:"thread_id"`
	UserID          string             `json:"user_id"`
	Goal            string             `json:"goal"`
	Status          string             `json:"status"`
	WorkflowKind    string             `json:"workflow_kind"`
	Mode            pgtype.Text        `json:"mode"`
	CurrentNode     pgtype.Text        `json:"current_node"`
	ParentRunID     pgtype.Text        `json:"parent_run_id"`
	PlannerVersion  pgtype.Text        `json:"planner_version"`
	AgentRole       pgtype.Text        `json:"agent_role"`
	TraceGroupID    pgtype.Text        `json:"trace_group_id"`
	CheckpointID    pgtype.Text        `json:"checkpoint_id"`
	CheckpointState []byte             `json:"checkpoint_state"`
	BudgetState     []byte             `json:"budget_state"`
	ResponseText    pgtype.Text        `json:"response_text"`
	Error           pgtype.Text        `json:"error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlRunEvent struct {
	EventID        string             `json:"event_id"`
	SequenceNumber int64              `json:"sequence_number"`
	RunID          string             `json:"run_id"`
	ThreadID       pgtype.Text        `json:"thread_id"`
	EventKind      string             `json:"event_kind"`
	EventType      pgtype.Text        `json:"event_type"`
	NodeName       pgtype.Text        `json:"node_name"`
	TaskID         pgtype.Text        `json:"task_id"`
	CheckpointID   pgtype.Text        `json:"checkpoint_id"`
	ScopeID        pgtype.Text        `json:"scope_id"`
	AgentRole      pgtype.Text        `json:"agent_role"`
	Level          pgtype.Text        `json:"level"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Message        pgtype.Text        `json:"message"`
	Payload        []byte             `json:"payload"`
}

type ControlRunLease struct {
	RunID          string             `json:"run_id"`
	WorkerID       string             `json:"worker_id"`
	LeaseToken     string             `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlThread struct {
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LatestRunID  pgtype.Text        `json:"latest_run_id"`
	CheckpointID pgtype.Text        `json:"checkpoint_id"`
	Summary      pgtype.Text        `json:"summary"`
	Metadata     []byte             `json:"metadata"`
}

type ControlThreadMessage struct {
	MessageID string             `json:"message_id"`
	ThreadID  string             `json:"thread_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	RunID     pgtype.Text        `json:"run_id"`
}

type ControlUser struct {
	UserID      string             `json:"user_id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	OrgID       pgtype.Text        `json:"org_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Metadata    []byte             `json:"metadata"`
}

type ControlWorkerHeartbeat struct {
	WorkerID        string             `json:"worker_id"`
	WorkerKind      string             `json:"worker_kind"`
	Status          string             `json:"status"`
	CurrentRunID    pgtype.Text        `json:"current_run_id"`
	Hostname        pgtype.Text        `json:"hostname"`
	Version         pgtype.Text        `json:"version"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Metadata        []byte             `json:"metadata"`
}
