// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlArtifact struct {
	ArtifactID    string             `json:"artifact_id"`
	RunID         string             `json:"run_id"`
	ThreadID      pgtype.Text        `json:"thread_id"`
	Kind          string             `json:"kind"`
	Path          pgtype.Text        `json:"path"`
	SourcePath    pgtype.Text        `json:"source_path"`
	PreviewPath   pgtype.Text        `json:"preview_path"`
	Title         pgtype.Text        `json:"title"`
	ResultGroupID pgtype.Text        `json:"result_group_id"`
	MimeType      pgtype.Text        `json:"mime_type"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	Sha256        pgtype.Text        `json:"sha256"`
	StorageUri    pgtype.Text        `json:"storage_uri"`
	ToolName      pgtype.Text        `json:"tool_name"`
	Category      pgtype.Text        `json:"category"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Metadata      []byte             `json:"metadata"`
}

type ControlBisqueCredential struct {
	SessionID          string             `json:"session_id"`
	UserID             string             `json:"user_id"`
	OrgID              pgtype.Text        `json:"org_id"`
	RootUrl            string             `json:"root_url"`
	Username           string             `json:"username"`
	PasswordCiphertext string             `json:"password_ciphertext"`
	PasswordNonce      string             `json:"password_nonce"`
	PasswordKeyID      string             `json:"password_key_id"`
	PasswordAlgorithm  string             `json:"password_algorithm"`
	Status             string             `json:"status"`
	LastVerifiedAt     pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlDataAgentJob struct {
	JobID             string             `json:"job_id"`
	OwnerUserID       string             `json:"owner_user_id"`
	OwnerOrgID        pgtype.Text        `json:"owner_org_id"`
	OwnerRole         pgtype.Text        `json:"owner_role"`
	ProjectID         pgtype.Text        `json:"project_id"`
	JobType           string             `json:"job_type"`
	Status            string             `json:"status"`
	ResourceCount     int64              `json:"resource_count"`
	ProgressCompleted int64              `json:"progress_completed"`
	ProgressTotal     int64              `json:"progress_total"`
	Error             pgtype.Text        `json:"error"`
	CreatedByUserID   pgtype.Text        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	InputSelector     []byte             `json:"input_selector"`
	OutputSummary     []byte             `json:"output_summary"`
	Metadata          []byte             `json:"metadata"`
}

type ControlDataAgentJobEvent struct {
	EventID     string             `json:"event_id"`
	JobID       string             `json:"job_id"`
	Sequence    int64              `json:"sequence"`
	EventType   string             `json:"event_type"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Message     pgtype.Text        `json:"message"`
	Metadata    []byte             `json:"metadata"`
}

type ControlDataAgentJobLease struct {
	JobID          string             `json:"job_id"`
	WorkerID       string             `json:"worker_id"`
	LeaseToken     string             `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlDataAgentJobResource struct {
	JobID      string `json:"job_id"`
	ResourceID string `json:"resource_id"`
	Position   int64  `json:"position"`
	Metadata   []byte `json:"metadata"`
	IoRole     string `json:"io_role"`
}

type ControlDatasetSnapshot struct {
	SnapshotID         string             `json:"snapshot_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	ProjectID          pgtype.Text        `json:"project_id"`
	SourceCollectionID pgtype.Text        `json:"source_collection_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Status             string             `json:"status"`
	ResourceCount      int64              `json:"resource_count"`
	TotalBytes         int64              `json:"total_bytes"`
	CreatedByUserID    pgtype.Text        `json:"created_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlDatasetSnapshotEvent struct {
	EventID     string             `json:"event_id"`
	SnapshotID  string             `json:"snapshot_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

type ControlDatasetSnapshotResource struct {
	SnapshotID        string             `json:"snapshot_id"`
	ResourceID        string             `json:"resource_id"`
	Position          int64              `json:"position"`
	OriginalName      string             `json:"original_name"`
	ContentType       pgtype.Text        `json:"content_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Sha256            pgtype.Text        `json:"sha256"`
	SourceType        string             `json:"source_type"`
	ResourceKind      string             `json:"resource_kind"`
	StorageUri        pgtype.Text        `json:"storage_uri"`
	SourceUri         pgtype.Text        `json:"source_uri"`
	ProjectID         pgtype.Text        `json:"project_id"`
	ResourceCreatedAt pgtype.Timestamptz `json:"resource_created_at"`
	Metadata          []byte             `json:"metadata"`
}

type ControlDatasetSnapshotShareGrant struct {
	GrantID         string             `json:"grant_id"`
	SnapshotID      string             `json:"snapshot_id"`
	OwnerUserID     string             `json:"owner_user_id"`
	OwnerOrgID      pgtype.Text        `json:"owner_org_id"`
	OwnerRole       pgtype.Text        `json:"owner_role"`
	GranteeUserID   pgtype.Text        `json:"grantee_user_id"`
	GranteeOrgID    pgtype.Text        `json:"grantee_org_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.Text        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlOrganization struct {
	OrgID     string             `json:"org_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Metadata  []byte             `json:"metadata"`
}

type ControlResource struct {
	ResourceID         string             `json:"resource_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	OriginalName       string             `json:"original_name"`
	ContentType        pgtype.Text        `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             pgtype.Text        `json:"sha256"`
	StorageUri         pgtype.Text        `json:"storage_uri"`
	StoragePath        pgtype.Text        `json:"storage_path"`
	SourceType         string             `json:"source_type"`
	ResourceKind       string             `json:"resource_kind"`
	SourceUri          pgtype.Text        `json:"source_uri"`
	ProjectID          pgtype.Text        `json:"project_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	RetentionExpiresAt pgtype.Timestamptz `json:"retention_expires_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlResourceCollection struct {
	CollectionID       string             `json:"collection_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	ProjectID          pgtype.Text        `json:"project_id"`
	ParentCollectionID pgtype.Text        `json:"parent_collection_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	CollectionType     string             `json:"collection_type"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlResourceCollectionMember struct {
	CollectionID  string             `json:"collection_id"`
	ResourceID    string             `json:"resource_id"`
	Position      int64              `json:"position"`
	AddedByUserID pgtype.Text        `json:"added_by_user_id"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
	Metadata      []byte             `json:"metadata"`
}

type ControlResourceCollectionShareGrant struct {
	GrantID         string             `json:"grant_id"`
	CollectionID    string             `json:"collection_id"`
	OwnerUserID     string             `json:"owner_user_id"`
	OwnerOrgID      pgtype.Text        `json:"owner_org_id"`
	OwnerRole       pgtype.Text        `json:"owner_role"`
	GranteeUserID   pgtype.Text        `json:"grantee_user_id"`
	GranteeOrgID    pgtype.Text        `json:"grantee_org_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.Text        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlResourceEvent struct {
	EventID     string             `json:"event_id"`
	ResourceID  string             `json:"resource_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

type ControlResourceSearchDocument struct {
	ResourceID   string             `json:"resource_id"`
	OwnerUserID  string             `json:"owner_user_id"`
	OwnerOrgID   pgtype.Text        `json:"owner_org_id"`
	ProjectID    pgtype.Text        `json:"project_id"`
	Status       string             `json:"status"`
	SearchText   string             `json:"search_text"`
	SearchVector interface{}        `json:"search_vector"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ControlResourceSearchFact struct {
	ResourceID  string             `json:"resource_id"`
	OwnerUserID string             `json:"owner_user_id"`
	OwnerOrgID  pgtype.Text        `json:"owner_org_id"`
	ProjectID   pgtype.Text        `json:"project_id"`
	Status      string             `json:"status"`
	FactKey     string             `json:"fact_key"`
	FactText    string             `json:"fact_text"`
	FactNumber  pgtype.Float8      `json:"fact_number"`
	FactSource  string             `json:"fact_source"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ControlResourceShareGrant struct {
	GrantID         string             `json:"grant_id"`
	ResourceID      string             `json:"resource_id"`
	OwnerUserID     string             `json:"owner_user_id"`
	OwnerOrgID      pgtype.Text        `json:"owner_org_id"`
	OwnerRole       pgtype.Text        `json:"owner_role"`
	GranteeUserID   pgtype.Text        `json:"grantee_user_id"`
	GranteeOrgID    pgtype.Text        `json:"grantee_org_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.Text        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlRun struct {
	RunID           string             `json:"run_id"`
	ThreadID        string             `json:"thread_id"`
	UserID          string             `json:"user_id"`
	Goal            string             `json:"goal"`
	Status          string             `json:"status"`
	WorkflowKind    string             `json:"workflow_kind"`
	Mode            pgtype.Text        `json:"mode"`
	CurrentNode     pgtype.Text        `json:"current_node"`
	ParentRunID     pgtype.Text        `json:"parent_run_id"`
	PlannerVersion  pgtype.Text        `json:"planner_version"`
	AgentRole       pgtype.Text        `json:"agent_role"`
	TraceGroupID    pgtype.Text        `json:"trace_group_id"`
	CheckpointID    pgtype.Text        `json:"checkpoint_id"`
	CheckpointState []byte             `json:"checkpoint_state"`
	BudgetState     []byte             `json:"budget_state"`
	ResponseText    pgtype.Text        `json:"response_text"`
	Error           pgtype.Text        `json:"error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Metadata        []byte             `json:"metadata"`
}

type ControlRunEvent struct {
	EventID        string             `json:"event_id"`
	SequenceNumber int64              `json:"sequence_number"`
	RunID          string             `json:"run_id"`
	ThreadID       pgtype.Text        `json:"thread_id"`
	EventKind      string             `json:"event_kind"`
	EventType      pgtype.Text        `json:"event_type"`
	NodeName       pgtype.Text        `json:"node_name"`
	TaskID         pgtype.Text        `json:"task_id"`
	CheckpointID   pgtype.Text        `json:"checkpoint_id"`
	ScopeID        pgtype.Text        `json:"scope_id"`
	AgentRole      pgtype.Text        `json:"agent_role"`
	Level          pgtype.Text        `json:"level"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Message        pgtype.Text        `json:"message"`
	Payload        []byte             `json:"payload"`
}

type ControlRunEventSequence struct {
	RunID        string `json:"run_id"`
	LastSequence int64  `json:"last_sequence"`
}

type ControlRunLease struct {
	RunID          string             `json:"run_id"`
	WorkerID       string             `json:"worker_id"`
	LeaseToken     string             `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlRunTokenUsage struct {
	RunID        string             `json:"run_id"`
	UsageEventID string             `json:"usage_event_id"`
	UserID       string             `json:"user_id"`
	Model        string             `json:"model"`
	Day          pgtype.Date        `json:"day"`
	InputTokens  int64              `json:"input_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ControlRunTokenUsageFinalized struct {
	RunID       string             `json:"run_id"`
	UserID      string             `json:"user_id"`
	Day         pgtype.Date        `json:"day"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
}

type ControlThread struct {
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LatestRunID  pgtype.Text        `json:"latest_run_id"`
	CheckpointID pgtype.Text        `json:"checkpoint_id"`
	Summary      pgtype.Text        `json:"summary"`
	Metadata     []byte             `json:"metadata"`
}

type ControlThreadMessage struct {
	MessageID string             `json:"message_id"`
	ThreadID  string             `json:"thread_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	RunID     pgtype.Text        `json:"run_id"`
}

type ControlUploadChunk struct {
	SessionID  string             `json:"session_id"`
	FileToken  string             `json:"file_token"`
	ChunkIndex int32              `json:"chunk_index"`
	ByteOffset int64              `json:"byte_offset"`
	SizeBytes  int64              `json:"size_bytes"`
	Sha256     string             `json:"sha256"`
	Status     string             `json:"status"`
	StorageUri pgtype.Text        `json:"storage_uri"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	Error      pgtype.Text        `json:"error"`
	Metadata   []byte             `json:"metadata"`
}

type ControlUploadSession struct {
	SessionID          string             `json:"session_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	ProjectID          pgtype.Text        `json:"project_id"`
	SourceType         string             `json:"source_type"`
	Status             string             `json:"status"`
	TotalBytes         int64              `json:"total_bytes"`
	BytesReceived      int64              `json:"bytes_received"`
	BytesVerified      int64              `json:"bytes_verified"`
	BytesCommitted     int64              `json:"bytes_committed"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	BrowserFingerprint pgtype.Text        `json:"browser_fingerprint"`
	Error              pgtype.Text        `json:"error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	Metadata           []byte             `json:"metadata"`
}

type ControlUploadSessionEvent struct {
	EventID     string             `json:"event_id"`
	SessionID   string             `json:"session_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

type ControlUploadSessionFile struct {
	SessionID      string             `json:"session_id"`
	FileToken      string             `json:"file_token"`
	ResourceID     pgtype.Text        `json:"resource_id"`
	OriginalName   string             `json:"original_name"`
	RelativePath   pgtype.Text        `json:"relative_path"`
	ContentType    pgtype.Text        `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	DeclaredSha256 pgtype.Text        `json:"declared_sha256"`
	ComputedSha256 pgtype.Text        `json:"computed_sha256"`
	Status         string             `json:"status"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Metadata       []byte             `json:"metadata"`
}

type ControlUser struct {
	UserID      string             `json:"user_id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	OrgID       pgtype.Text        `json:"org_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Metadata    []byte             `json:"metadata"`
}

type ControlUserTokenUsageDaily struct {
	UserID       string             `json:"user_id"`
	Day          pgtype.Date        `json:"day"`
	InputTokens  int64              `json:"input_tokens"`
	OutputTokens int64              `json:"output_tokens"`
	TotalTokens  int64              `json:"total_tokens"`
	RunCount     int64              `json:"run_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ControlUserTokenUsageLifetime struct {
	UserID         string             `json:"user_id"`
	InputTokens    int64              `json:"input_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	TotalTokens    int64              `json:"total_tokens"`
	PeakDailyTotal int64              `json:"peak_daily_total"`
	LastActiveDay  pgtype.Date        `json:"last_active_day"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ControlWorkerHeartbeat struct {
	WorkerID        string             `json:"worker_id"`
	WorkerKind      string             `json:"worker_kind"`
	Status          string             `json:"status"`
	CurrentRunID    pgtype.Text        `json:"current_run_id"`
	Hostname        pgtype.Text        `json:"hostname"`
	Version         pgtype.Text        `json:"version"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Metadata        []byte             `json:"metadata"`
}
