// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendRunEvent = `-- name: AppendRunEvent :one
INSERT INTO control_run_events (
  event_id, sequence_number, run_id, thread_id, event_kind, event_type,
  node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
`

type AppendRunEventParams struct {
	EventID        string             `json:"event_id"`
	SequenceNumber int64              `json:"sequence_number"`
	RunID          string             `json:"run_id"`
	ThreadID       pgtype.Text        `json:"thread_id"`
	EventKind      string             `json:"event_kind"`
	EventType      pgtype.Text        `json:"event_type"`
	NodeName       pgtype.Text        `json:"node_name"`
	TaskID         pgtype.Text        `json:"task_id"`
	CheckpointID   pgtype.Text        `json:"checkpoint_id"`
	ScopeID        pgtype.Text        `json:"scope_id"`
	AgentRole      pgtype.Text        `json:"agent_role"`
	Level          pgtype.Text        `json:"level"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Message        pgtype.Text        `json:"message"`
	Payload        []byte             `json:"payload"`
}

func (q *Queries) AppendRunEvent(ctx context.Context, arg AppendRunEventParams) (ControlRunEvent, error) {
	row := q.db.QueryRow(ctx, appendRunEvent,
		arg.EventID,
		arg.SequenceNumber,
		arg.RunID,
		arg.ThreadID,
		arg.EventKind,
		arg.EventType,
		arg.NodeName,
		arg.TaskID,
		arg.CheckpointID,
		arg.ScopeID,
		arg.AgentRole,
		arg.Level,
		arg.Ts,
		arg.Message,
		arg.Payload,
	)
	var i ControlRunEvent
	err := row.Scan(
		&i.EventID,
		&i.SequenceNumber,
		&i.RunID,
		&i.ThreadID,
		&i.EventKind,
		&i.EventType,
		&i.NodeName,
		&i.TaskID,
		&i.CheckpointID,
		&i.ScopeID,
		&i.AgentRole,
		&i.Level,
		&i.Ts,
		&i.Message,
		&i.Payload,
	)
	return i, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO control_artifacts (
  artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title,
  result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category,
  created_at, updated_at, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title, result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category, created_at, updated_at, metadata
`

type CreateArtifactParams struct {
	ArtifactID    string             `json:"artifact_id"`
	RunID         string             `json:"run_id"`
	ThreadID      pgtype.Text        `json:"thread_id"`
	Kind          string             `json:"kind"`
	Path          pgtype.Text        `json:"path"`
	SourcePath    pgtype.Text        `json:"source_path"`
	PreviewPath   pgtype.Text        `json:"preview_path"`
	Title         pgtype.Text        `json:"title"`
	ResultGroupID pgtype.Text        `json:"result_group_id"`
	MimeType      pgtype.Text        `json:"mime_type"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	Sha256        pgtype.Text        `json:"sha256"`
	StorageUri    pgtype.Text        `json:"storage_uri"`
	ToolName      pgtype.Text        `json:"tool_name"`
	Category      pgtype.Text        `json:"category"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Metadata      []byte             `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (ControlArtifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ArtifactID,
		arg.RunID,
		arg.ThreadID,
		arg.Kind,
		arg.Path,
		arg.SourcePath,
		arg.PreviewPath,
		arg.Title,
		arg.ResultGroupID,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.StorageUri,
		arg.ToolName,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	var i ControlArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.RunID,
		&i.ThreadID,
		&i.Kind,
		&i.Path,
		&i.SourcePath,
		&i.PreviewPath,
		&i.Title,
		&i.ResultGroupID,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.ToolName,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO control_runs (run_id, thread_id, user_id, goal, status, workflow_kind, mode, created_at, updated_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata
`

type CreateRunParams struct {
	RunID        string             `json:"run_id"`
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Goal         string             `json:"goal"`
	Status       string             `json:"status"`
	WorkflowKind string             `json:"workflow_kind"`
	Mode         pgtype.Text        `json:"mode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Metadata     []byte             `json:"metadata"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (ControlRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.RunID,
		arg.ThreadID,
		arg.UserID,
		arg.Goal,
		arg.Status,
		arg.WorkflowKind,
		arg.Mode,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO control_threads (thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata
`

type CreateThreadParams struct {
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LatestRunID  pgtype.Text        `json:"latest_run_id"`
	CheckpointID pgtype.Text        `json:"checkpoint_id"`
	Summary      pgtype.Text        `json:"summary"`
	Metadata     []byte             `json:"metadata"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (ControlThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ThreadID,
		arg.UserID,
		arg.Title,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LatestRunID,
		arg.CheckpointID,
		arg.Summary,
		arg.Metadata,
	)
	var i ControlThread
	err := row.Scan(
		&i.ThreadID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRunID,
		&i.CheckpointID,
		&i.Summary,
		&i.Metadata,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title, result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category, created_at, updated_at, metadata FROM control_artifacts WHERE artifact_id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, artifactID string) (ControlArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, artifactID)
	var i ControlArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.RunID,
		&i.ThreadID,
		&i.Kind,
		&i.Path,
		&i.SourcePath,
		&i.PreviewPath,
		&i.Title,
		&i.ResultGroupID,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.ToolName,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata FROM control_runs WHERE run_id = $1
`

func (q *Queries) GetRun(ctx context.Context, runID string) (ControlRun, error) {
	row := q.db.QueryRow(ctx, getRun, runID)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const getRunEvent = `-- name: GetRunEvent :one
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload FROM control_run_events WHERE event_id = $1
`

func (q *Queries) GetRunEvent(ctx context.Context, eventID string) (ControlRunEvent, error) {
	row := q.db.QueryRow(ctx, getRunEvent, eventID)
	var i ControlRunEvent
	err := row.Scan(
		&i.EventID,
		&i.SequenceNumber,
		&i.RunID,
		&i.ThreadID,
		&i.EventKind,
		&i.EventType,
		&i.NodeName,
		&i.TaskID,
		&i.CheckpointID,
		&i.ScopeID,
		&i.AgentRole,
		&i.Level,
		&i.Ts,
		&i.Message,
		&i.Payload,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata FROM control_threads WHERE thread_id = $1
`

func (q *Queries) GetThread(ctx context.Context, threadID string) (ControlThread, error) {
	row := q.db.QueryRow(ctx, getThread, threadID)
	var i ControlThread
	err := row.Scan(
		&i.ThreadID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRunID,
		&i.CheckpointID,
		&i.Summary,
		&i.Metadata,
	)
	return i, err
}

const insertThreadMessage = `-- name: InsertThreadMessage :one
INSERT INTO control_thread_messages (message_id, thread_id, role, content, created_at, metadata, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING message_id, thread_id, role, content, created_at, metadata, run_id
`

type InsertThreadMessageParams struct {
	MessageID string             `json:"message_id"`
	ThreadID  string             `json:"thread_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	RunID     pgtype.Text        `json:"run_id"`
}

func (q *Queries) InsertThreadMessage(ctx context.Context, arg InsertThreadMessageParams) (ControlThreadMessage, error) {
	row := q.db.QueryRow(ctx, insertThreadMessage,
		arg.MessageID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
		arg.Metadata,
		arg.RunID,
	)
	var i ControlThreadMessage
	err := row.Scan(
		&i.MessageID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.Metadata,
		&i.RunID,
	)
	return i, err
}

const listRunArtifacts = `-- name: ListRunArtifacts :many
SELECT artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title, result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category, created_at, updated_at, metadata FROM control_artifacts WHERE run_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListRunArtifactsParams struct {
	RunID string `json:"run_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListRunArtifacts(ctx context.Context, arg ListRunArtifactsParams) ([]ControlArtifact, error) {
	rows, err := q.db.Query(ctx, listRunArtifacts, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlArtifact
	for rows.Next() {
		var i ControlArtifact
		if err := rows.Scan(
			&i.ArtifactID,
			&i.RunID,
			&i.ThreadID,
			&i.Kind,
			&i.Path,
			&i.SourcePath,
			&i.PreviewPath,
			&i.Title,
			&i.ResultGroupID,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageUri,
			&i.ToolName,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
FROM (
  SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload FROM control_run_events WHERE run_id = $1 ORDER BY sequence_number DESC LIMIT $2
) recent_events
ORDER BY sequence_number ASC
`

type ListRunEventsParams struct {
	RunID string `json:"run_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]ControlRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRunEvent
	for rows.Next() {
		var i ControlRunEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SequenceNumber,
			&i.RunID,
			&i.ThreadID,
			&i.EventKind,
			&i.EventType,
			&i.NodeName,
			&i.TaskID,
			&i.CheckpointID,
			&i.ScopeID,
			&i.AgentRole,
			&i.Level,
			&i.Ts,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEventsAfter = `-- name: ListRunEventsAfter :many
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
FROM control_run_events
WHERE run_id = $1 AND sequence_number > $2
ORDER BY sequence_number ASC
LIMIT $3
`

type ListRunEventsAfterParams struct {
	RunID          string `json:"run_id"`
	SequenceNumber int64  `json:"sequence_number"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListRunEventsAfter(ctx context.Context, arg ListRunEventsAfterParams) ([]ControlRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsAfter, arg.RunID, arg.SequenceNumber, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRunEvent
	for rows.Next() {
		var i ControlRunEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SequenceNumber,
			&i.RunID,
			&i.ThreadID,
			&i.EventKind,
			&i.EventType,
			&i.NodeName,
			&i.TaskID,
			&i.CheckpointID,
			&i.ScopeID,
			&i.AgentRole,
			&i.Level,
			&i.Ts,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata FROM control_runs
WHERE ($1::text = '' OR thread_id = $1)
  AND ($2::text = '' OR status = $2)
ORDER BY updated_at DESC
LIMIT $3 OFFSET $4
`

type ListRunsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ControlRun, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRun
	for rows.Next() {
		var i ControlRun
		if err := rows.Scan(
			&i.RunID,
			&i.ThreadID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.WorkflowKind,
			&i.Mode,
			&i.CurrentNode,
			&i.ParentRunID,
			&i.PlannerVersion,
			&i.AgentRole,
			&i.TraceGroupID,
			&i.CheckpointID,
			&i.CheckpointState,
			&i.BudgetState,
			&i.ResponseText,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT message_id, thread_id, role, content, created_at, metadata, run_id FROM control_thread_messages WHERE thread_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListThreadMessages(ctx context.Context, threadID string) ([]ControlThreadMessage, error) {
	rows, err := q.db.Query(ctx, listThreadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlThreadMessage
	for rows.Next() {
		var i ControlThreadMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.Metadata,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata FROM control_threads ORDER BY updated_at DESC LIMIT $1
`

func (q *Queries) ListThreads(ctx context.Context, limit int32) ([]ControlThread, error) {
	rows, err := q.db.Query(ctx, listThreads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlThread
	for rows.Next() {
		var i ControlThread
		if err := rows.Scan(
			&i.ThreadID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestRunID,
			&i.CheckpointID,
			&i.Summary,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunEventSequence = `-- name: NextRunEventSequence :one
SELECT COALESCE(MAX(sequence_number), 0) + 1 AS next_sequence FROM control_run_events WHERE run_id = $1
`

func (q *Queries) NextRunEventSequence(ctx context.Context, runID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextRunEventSequence, runID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const setThreadLatestRun = `-- name: SetThreadLatestRun :exec
UPDATE control_threads SET latest_run_id = $2, updated_at = $3 WHERE thread_id = $1
`

type SetThreadLatestRunParams struct {
	ThreadID    string             `json:"thread_id"`
	LatestRunID pgtype.Text        `json:"latest_run_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetThreadLatestRun(ctx context.Context, arg SetThreadLatestRunParams) error {
	_, err := q.db.Exec(ctx, setThreadLatestRun, arg.ThreadID, arg.LatestRunID, arg.UpdatedAt)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE control_runs
SET status = $2,
    response_text = NULLIF($3, ''),
    error = NULLIF($4, ''),
    updated_at = $5,
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN $5 ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('succeeded', 'failed', 'canceled') THEN $5 ELSE completed_at END
WHERE run_id = $1
  AND status NOT IN ('succeeded', 'failed', 'canceled')
RETURNING run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata
`

type UpdateRunStatusParams struct {
	RunID     string             `json:"run_id"`
	Status    string             `json:"status"`
	Column3   interface{}        `json:"column_3"`
	Column4   interface{}        `json:"column_4"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (ControlRun, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.RunID,
		arg.Status,
		arg.Column3,
		arg.Column4,
		arg.UpdatedAt,
	)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}
