// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendRunEvent = `-- name: AppendRunEvent :one
INSERT INTO control_run_events (
  event_id, sequence_number, run_id, thread_id, event_kind, event_type,
  node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
`

type AppendRunEventParams struct {
	EventID        string             `json:"event_id"`
	SequenceNumber int64              `json:"sequence_number"`
	RunID          string             `json:"run_id"`
	ThreadID       pgtype.Text        `json:"thread_id"`
	EventKind      string             `json:"event_kind"`
	EventType      pgtype.Text        `json:"event_type"`
	NodeName       pgtype.Text        `json:"node_name"`
	TaskID         pgtype.Text        `json:"task_id"`
	CheckpointID   pgtype.Text        `json:"checkpoint_id"`
	ScopeID        pgtype.Text        `json:"scope_id"`
	AgentRole      pgtype.Text        `json:"agent_role"`
	Level          pgtype.Text        `json:"level"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Message        pgtype.Text        `json:"message"`
	Payload        []byte             `json:"payload"`
}

func (q *Queries) AppendRunEvent(ctx context.Context, arg AppendRunEventParams) (ControlRunEvent, error) {
	row := q.db.QueryRow(ctx, appendRunEvent,
		arg.EventID,
		arg.SequenceNumber,
		arg.RunID,
		arg.ThreadID,
		arg.EventKind,
		arg.EventType,
		arg.NodeName,
		arg.TaskID,
		arg.CheckpointID,
		arg.ScopeID,
		arg.AgentRole,
		arg.Level,
		arg.Ts,
		arg.Message,
		arg.Payload,
	)
	var i ControlRunEvent
	err := row.Scan(
		&i.EventID,
		&i.SequenceNumber,
		&i.RunID,
		&i.ThreadID,
		&i.EventKind,
		&i.EventType,
		&i.NodeName,
		&i.TaskID,
		&i.CheckpointID,
		&i.ScopeID,
		&i.AgentRole,
		&i.Level,
		&i.Ts,
		&i.Message,
		&i.Payload,
	)
	return i, err
}

const countResourcesForUser = `-- name: CountResourcesForUser :one
SELECT count(*)::bigint
FROM control_resources
WHERE owner_user_id = $1
  AND (COALESCE(owner_org_id, '') = '' OR owner_org_id = $2)
  AND status = $3
  AND ($4::text = '' OR resource_kind = $4)
  AND ($5::text = '' OR source_type = $5)
  AND ($6::text = '' OR project_id = $6)
  AND (
    $7::text = ''
    OR lower(resource_id) LIKE '%' || lower($7::text) || '%'
    OR lower(original_name) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(source_uri, '')) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(content_type, '')) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(sha256, '')) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(project_id, '')) LIKE '%' || lower($7::text) || '%'
  )
`

type CountResourcesForUserParams struct {
	OwnerUserID string      `json:"owner_user_id"`
	OwnerOrgID  pgtype.Text `json:"owner_org_id"`
	Status      string      `json:"status"`
	Column4     string      `json:"column_4"`
	Column5     string      `json:"column_5"`
	Column6     string      `json:"column_6"`
	Column7     string      `json:"column_7"`
}

func (q *Queries) CountResourcesForUser(ctx context.Context, arg CountResourcesForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesForUser,
		arg.OwnerUserID,
		arg.OwnerOrgID,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countThreads = `-- name: CountThreads :one
SELECT COUNT(*) FROM control_threads
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountThreads(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countThreads, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThreadsForUser = `-- name: CountThreadsForUser :one
SELECT COUNT(*) FROM control_threads
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
`

type CountThreadsForUserParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountThreadsForUser(ctx context.Context, arg CountThreadsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countThreadsForUser, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO control_artifacts (
  artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title,
  result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category,
  created_at, updated_at, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title, result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category, created_at, updated_at, metadata
`

type CreateArtifactParams struct {
	ArtifactID    string             `json:"artifact_id"`
	RunID         string             `json:"run_id"`
	ThreadID      pgtype.Text        `json:"thread_id"`
	Kind          string             `json:"kind"`
	Path          pgtype.Text        `json:"path"`
	SourcePath    pgtype.Text        `json:"source_path"`
	PreviewPath   pgtype.Text        `json:"preview_path"`
	Title         pgtype.Text        `json:"title"`
	ResultGroupID pgtype.Text        `json:"result_group_id"`
	MimeType      pgtype.Text        `json:"mime_type"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	Sha256        pgtype.Text        `json:"sha256"`
	StorageUri    pgtype.Text        `json:"storage_uri"`
	ToolName      pgtype.Text        `json:"tool_name"`
	Category      pgtype.Text        `json:"category"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Metadata      []byte             `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (ControlArtifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ArtifactID,
		arg.RunID,
		arg.ThreadID,
		arg.Kind,
		arg.Path,
		arg.SourcePath,
		arg.PreviewPath,
		arg.Title,
		arg.ResultGroupID,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.StorageUri,
		arg.ToolName,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	var i ControlArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.RunID,
		&i.ThreadID,
		&i.Kind,
		&i.Path,
		&i.SourcePath,
		&i.PreviewPath,
		&i.Title,
		&i.ResultGroupID,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.ToolName,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const createResourceEvent = `-- name: CreateResourceEvent :one
INSERT INTO control_resource_events (
  event_id, resource_id, actor_user_id, actor_org_id, event_type, ts, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING event_id, resource_id, actor_user_id, actor_org_id, event_type, ts, metadata
`

type CreateResourceEventParams struct {
	EventID     string             `json:"event_id"`
	ResourceID  string             `json:"resource_id"`
	ActorUserID pgtype.Text        `json:"actor_user_id"`
	ActorOrgID  pgtype.Text        `json:"actor_org_id"`
	EventType   string             `json:"event_type"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) CreateResourceEvent(ctx context.Context, arg CreateResourceEventParams) (ControlResourceEvent, error) {
	row := q.db.QueryRow(ctx, createResourceEvent,
		arg.EventID,
		arg.ResourceID,
		arg.ActorUserID,
		arg.ActorOrgID,
		arg.EventType,
		arg.Ts,
		arg.Metadata,
	)
	var i ControlResourceEvent
	err := row.Scan(
		&i.EventID,
		&i.ResourceID,
		&i.ActorUserID,
		&i.ActorOrgID,
		&i.EventType,
		&i.Ts,
		&i.Metadata,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO control_runs (run_id, thread_id, user_id, goal, status, workflow_kind, mode, created_at, updated_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata
`

type CreateRunParams struct {
	RunID        string             `json:"run_id"`
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Goal         string             `json:"goal"`
	Status       string             `json:"status"`
	WorkflowKind string             `json:"workflow_kind"`
	Mode         pgtype.Text        `json:"mode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Metadata     []byte             `json:"metadata"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (ControlRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.RunID,
		arg.ThreadID,
		arg.UserID,
		arg.Goal,
		arg.Status,
		arg.WorkflowKind,
		arg.Mode,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO control_threads (thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata
`

type CreateThreadParams struct {
	ThreadID     string             `json:"thread_id"`
	UserID       string             `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LatestRunID  pgtype.Text        `json:"latest_run_id"`
	CheckpointID pgtype.Text        `json:"checkpoint_id"`
	Summary      pgtype.Text        `json:"summary"`
	Metadata     []byte             `json:"metadata"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (ControlThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ThreadID,
		arg.UserID,
		arg.Title,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LatestRunID,
		arg.CheckpointID,
		arg.Summary,
		arg.Metadata,
	)
	var i ControlThread
	err := row.Scan(
		&i.ThreadID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRunID,
		&i.CheckpointID,
		&i.Summary,
		&i.Metadata,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title, result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category, created_at, updated_at, metadata FROM control_artifacts WHERE artifact_id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, artifactID string) (ControlArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, artifactID)
	var i ControlArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.RunID,
		&i.ThreadID,
		&i.Kind,
		&i.Path,
		&i.SourcePath,
		&i.PreviewPath,
		&i.Title,
		&i.ResultGroupID,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.ToolName,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getArtifactForUser = `-- name: GetArtifactForUser :one
SELECT a.artifact_id, a.run_id, a.thread_id, a.kind, a.path, a.source_path, a.preview_path, a.title, a.result_group_id, a.mime_type, a.size_bytes, a.sha256, a.storage_uri, a.tool_name, a.category, a.created_at, a.updated_at, a.metadata
FROM control_artifacts a
JOIN control_runs r ON r.run_id = a.run_id
WHERE a.artifact_id = $1
  AND r.user_id = $2
`

type GetArtifactForUserParams struct {
	ArtifactID string `json:"artifact_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetArtifactForUser(ctx context.Context, arg GetArtifactForUserParams) (ControlArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactForUser, arg.ArtifactID, arg.UserID)
	var i ControlArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.RunID,
		&i.ThreadID,
		&i.Kind,
		&i.Path,
		&i.SourcePath,
		&i.PreviewPath,
		&i.Title,
		&i.ResultGroupID,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.ToolName,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getResourceForUser = `-- name: GetResourceForUser :one
SELECT resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type, size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind, source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
FROM control_resources
WHERE resource_id = $1
  AND owner_user_id = $2
  AND (COALESCE(owner_org_id, '') = '' OR owner_org_id = $3)
  AND status = 'active'
`

type GetResourceForUserParams struct {
	ResourceID  string      `json:"resource_id"`
	OwnerUserID string      `json:"owner_user_id"`
	OwnerOrgID  pgtype.Text `json:"owner_org_id"`
}

func (q *Queries) GetResourceForUser(ctx context.Context, arg GetResourceForUserParams) (ControlResource, error) {
	row := q.db.QueryRow(ctx, getResourceForUser, arg.ResourceID, arg.OwnerUserID, arg.OwnerOrgID)
	var i ControlResource
	err := row.Scan(
		&i.ResourceID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.OwnerRole,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.StoragePath,
		&i.SourceType,
		&i.ResourceKind,
		&i.SourceUri,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RetentionExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata FROM control_runs WHERE run_id = $1
`

func (q *Queries) GetRun(ctx context.Context, runID string) (ControlRun, error) {
	row := q.db.QueryRow(ctx, getRun, runID)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const getRunEvent = `-- name: GetRunEvent :one
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload FROM control_run_events WHERE event_id = $1
`

func (q *Queries) GetRunEvent(ctx context.Context, eventID string) (ControlRunEvent, error) {
	row := q.db.QueryRow(ctx, getRunEvent, eventID)
	var i ControlRunEvent
	err := row.Scan(
		&i.EventID,
		&i.SequenceNumber,
		&i.RunID,
		&i.ThreadID,
		&i.EventKind,
		&i.EventType,
		&i.NodeName,
		&i.TaskID,
		&i.CheckpointID,
		&i.ScopeID,
		&i.AgentRole,
		&i.Level,
		&i.Ts,
		&i.Message,
		&i.Payload,
	)
	return i, err
}

const getRunForUser = `-- name: GetRunForUser :one
SELECT run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata FROM control_runs WHERE run_id = $1 AND user_id = $2
`

type GetRunForUserParams struct {
	RunID  string `json:"run_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRunForUser(ctx context.Context, arg GetRunForUserParams) (ControlRun, error) {
	row := q.db.QueryRow(ctx, getRunForUser, arg.RunID, arg.UserID)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata FROM control_threads WHERE thread_id = $1
`

func (q *Queries) GetThread(ctx context.Context, threadID string) (ControlThread, error) {
	row := q.db.QueryRow(ctx, getThread, threadID)
	var i ControlThread
	err := row.Scan(
		&i.ThreadID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRunID,
		&i.CheckpointID,
		&i.Summary,
		&i.Metadata,
	)
	return i, err
}

const getThreadForUser = `-- name: GetThreadForUser :one
SELECT thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata FROM control_threads WHERE thread_id = $1 AND user_id = $2
`

type GetThreadForUserParams struct {
	ThreadID string `json:"thread_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetThreadForUser(ctx context.Context, arg GetThreadForUserParams) (ControlThread, error) {
	row := q.db.QueryRow(ctx, getThreadForUser, arg.ThreadID, arg.UserID)
	var i ControlThread
	err := row.Scan(
		&i.ThreadID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestRunID,
		&i.CheckpointID,
		&i.Summary,
		&i.Metadata,
	)
	return i, err
}

const insertThreadMessage = `-- name: InsertThreadMessage :one
INSERT INTO control_thread_messages (message_id, thread_id, role, content, created_at, metadata, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING message_id, thread_id, role, content, created_at, metadata, run_id
`

type InsertThreadMessageParams struct {
	MessageID string             `json:"message_id"`
	ThreadID  string             `json:"thread_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	RunID     pgtype.Text        `json:"run_id"`
}

func (q *Queries) InsertThreadMessage(ctx context.Context, arg InsertThreadMessageParams) (ControlThreadMessage, error) {
	row := q.db.QueryRow(ctx, insertThreadMessage,
		arg.MessageID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
		arg.Metadata,
		arg.RunID,
	)
	var i ControlThreadMessage
	err := row.Scan(
		&i.MessageID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.Metadata,
		&i.RunID,
	)
	return i, err
}

const listResourceEvents = `-- name: ListResourceEvents :many
SELECT event_id, resource_id, actor_user_id, actor_org_id, event_type, ts, metadata
FROM control_resource_events
WHERE resource_id = $1
ORDER BY ts DESC, event_id ASC
LIMIT $2
`

type ListResourceEventsParams struct {
	ResourceID string `json:"resource_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListResourceEvents(ctx context.Context, arg ListResourceEventsParams) ([]ControlResourceEvent, error) {
	rows, err := q.db.Query(ctx, listResourceEvents, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlResourceEvent
	for rows.Next() {
		var i ControlResourceEvent
		if err := rows.Scan(
			&i.EventID,
			&i.ResourceID,
			&i.ActorUserID,
			&i.ActorOrgID,
			&i.EventType,
			&i.Ts,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type, size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind, source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
FROM control_resources
ORDER BY created_at DESC, resource_id ASC
LIMIT $1 OFFSET $2
`

type ListResourcesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ControlResource, error) {
	rows, err := q.db.Query(ctx, listResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlResource
	for rows.Next() {
		var i ControlResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.OwnerRole,
			&i.OriginalName,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageUri,
			&i.StoragePath,
			&i.SourceType,
			&i.ResourceKind,
			&i.SourceUri,
			&i.ProjectID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RetentionExpiresAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesForUser = `-- name: ListResourcesForUser :many
SELECT resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type, size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind, source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
FROM control_resources
WHERE owner_user_id = $1
  AND (COALESCE(owner_org_id, '') = '' OR owner_org_id = $2)
  AND status = $3
  AND ($4::text = '' OR resource_kind = $4)
  AND ($5::text = '' OR source_type = $5)
  AND ($6::text = '' OR project_id = $6)
  AND (
    $7::text = ''
    OR lower(resource_id) LIKE '%' || lower($7::text) || '%'
    OR lower(original_name) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(source_uri, '')) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(content_type, '')) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(sha256, '')) LIKE '%' || lower($7::text) || '%'
    OR lower(COALESCE(project_id, '')) LIKE '%' || lower($7::text) || '%'
  )
ORDER BY created_at DESC, resource_id ASC
LIMIT $8 OFFSET $9
`

type ListResourcesForUserParams struct {
	OwnerUserID string      `json:"owner_user_id"`
	OwnerOrgID  pgtype.Text `json:"owner_org_id"`
	Status      string      `json:"status"`
	Column4     string      `json:"column_4"`
	Column5     string      `json:"column_5"`
	Column6     string      `json:"column_6"`
	Column7     string      `json:"column_7"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListResourcesForUser(ctx context.Context, arg ListResourcesForUserParams) ([]ControlResource, error) {
	rows, err := q.db.Query(ctx, listResourcesForUser,
		arg.OwnerUserID,
		arg.OwnerOrgID,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlResource
	for rows.Next() {
		var i ControlResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.OwnerRole,
			&i.OriginalName,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageUri,
			&i.StoragePath,
			&i.SourceType,
			&i.ResourceKind,
			&i.SourceUri,
			&i.ProjectID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RetentionExpiresAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunArtifacts = `-- name: ListRunArtifacts :many
SELECT artifact_id, run_id, thread_id, kind, path, source_path, preview_path, title, result_group_id, mime_type, size_bytes, sha256, storage_uri, tool_name, category, created_at, updated_at, metadata FROM control_artifacts WHERE run_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListRunArtifactsParams struct {
	RunID string `json:"run_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListRunArtifacts(ctx context.Context, arg ListRunArtifactsParams) ([]ControlArtifact, error) {
	rows, err := q.db.Query(ctx, listRunArtifacts, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlArtifact
	for rows.Next() {
		var i ControlArtifact
		if err := rows.Scan(
			&i.ArtifactID,
			&i.RunID,
			&i.ThreadID,
			&i.Kind,
			&i.Path,
			&i.SourcePath,
			&i.PreviewPath,
			&i.Title,
			&i.ResultGroupID,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageUri,
			&i.ToolName,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunArtifactsForUser = `-- name: ListRunArtifactsForUser :many
SELECT a.artifact_id, a.run_id, a.thread_id, a.kind, a.path, a.source_path, a.preview_path, a.title, a.result_group_id, a.mime_type, a.size_bytes, a.sha256, a.storage_uri, a.tool_name, a.category, a.created_at, a.updated_at, a.metadata
FROM control_artifacts a
JOIN control_runs r ON r.run_id = a.run_id
WHERE a.run_id = $1
  AND r.user_id = $2
ORDER BY a.created_at DESC
LIMIT $3
`

type ListRunArtifactsForUserParams struct {
	RunID  string `json:"run_id"`
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListRunArtifactsForUser(ctx context.Context, arg ListRunArtifactsForUserParams) ([]ControlArtifact, error) {
	rows, err := q.db.Query(ctx, listRunArtifactsForUser, arg.RunID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlArtifact
	for rows.Next() {
		var i ControlArtifact
		if err := rows.Scan(
			&i.ArtifactID,
			&i.RunID,
			&i.ThreadID,
			&i.Kind,
			&i.Path,
			&i.SourcePath,
			&i.PreviewPath,
			&i.Title,
			&i.ResultGroupID,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageUri,
			&i.ToolName,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
FROM (
  SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload FROM control_run_events WHERE run_id = $1 ORDER BY sequence_number DESC LIMIT $2
) recent_events
ORDER BY sequence_number ASC
`

type ListRunEventsParams struct {
	RunID string `json:"run_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]ControlRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, arg.RunID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRunEvent
	for rows.Next() {
		var i ControlRunEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SequenceNumber,
			&i.RunID,
			&i.ThreadID,
			&i.EventKind,
			&i.EventType,
			&i.NodeName,
			&i.TaskID,
			&i.CheckpointID,
			&i.ScopeID,
			&i.AgentRole,
			&i.Level,
			&i.Ts,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEventsAfter = `-- name: ListRunEventsAfter :many
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
FROM control_run_events
WHERE run_id = $1 AND sequence_number > $2
ORDER BY sequence_number ASC
LIMIT $3
`

type ListRunEventsAfterParams struct {
	RunID          string `json:"run_id"`
	SequenceNumber int64  `json:"sequence_number"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListRunEventsAfter(ctx context.Context, arg ListRunEventsAfterParams) ([]ControlRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsAfter, arg.RunID, arg.SequenceNumber, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRunEvent
	for rows.Next() {
		var i ControlRunEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SequenceNumber,
			&i.RunID,
			&i.ThreadID,
			&i.EventKind,
			&i.EventType,
			&i.NodeName,
			&i.TaskID,
			&i.CheckpointID,
			&i.ScopeID,
			&i.AgentRole,
			&i.Level,
			&i.Ts,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEventsAfterForUser = `-- name: ListRunEventsAfterForUser :many
SELECT e.event_id, e.sequence_number, e.run_id, e.thread_id, e.event_kind, e.event_type, e.node_name, e.task_id, e.checkpoint_id, e.scope_id, e.agent_role, e.level, e.ts, e.message, e.payload
FROM control_run_events e
JOIN control_runs r ON r.run_id = e.run_id
WHERE e.run_id = $1
  AND r.user_id = $2
  AND e.sequence_number > $3
ORDER BY e.sequence_number ASC
LIMIT $4
`

type ListRunEventsAfterForUserParams struct {
	RunID          string `json:"run_id"`
	UserID         string `json:"user_id"`
	SequenceNumber int64  `json:"sequence_number"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListRunEventsAfterForUser(ctx context.Context, arg ListRunEventsAfterForUserParams) ([]ControlRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsAfterForUser,
		arg.RunID,
		arg.UserID,
		arg.SequenceNumber,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRunEvent
	for rows.Next() {
		var i ControlRunEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SequenceNumber,
			&i.RunID,
			&i.ThreadID,
			&i.EventKind,
			&i.EventType,
			&i.NodeName,
			&i.TaskID,
			&i.CheckpointID,
			&i.ScopeID,
			&i.AgentRole,
			&i.Level,
			&i.Ts,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEventsForUser = `-- name: ListRunEventsForUser :many
SELECT event_id, sequence_number, run_id, thread_id, event_kind, event_type, node_name, task_id, checkpoint_id, scope_id, agent_role, level, ts, message, payload
FROM (
  SELECT e.event_id, e.sequence_number, e.run_id, e.thread_id, e.event_kind, e.event_type, e.node_name, e.task_id, e.checkpoint_id, e.scope_id, e.agent_role, e.level, e.ts, e.message, e.payload
  FROM control_run_events e
  JOIN control_runs r ON r.run_id = e.run_id
  WHERE e.run_id = $1
    AND r.user_id = $2
  ORDER BY e.sequence_number DESC
  LIMIT $3
) recent_events
ORDER BY sequence_number ASC
`

type ListRunEventsForUserParams struct {
	RunID  string `json:"run_id"`
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListRunEventsForUser(ctx context.Context, arg ListRunEventsForUserParams) ([]ControlRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsForUser, arg.RunID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRunEvent
	for rows.Next() {
		var i ControlRunEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SequenceNumber,
			&i.RunID,
			&i.ThreadID,
			&i.EventKind,
			&i.EventType,
			&i.NodeName,
			&i.TaskID,
			&i.CheckpointID,
			&i.ScopeID,
			&i.AgentRole,
			&i.Level,
			&i.Ts,
			&i.Message,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata FROM control_runs
WHERE ($1::text = '' OR thread_id = $1)
  AND ($2::text = '' OR status = $2)
ORDER BY updated_at DESC
LIMIT $3 OFFSET $4
`

type ListRunsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ControlRun, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRun
	for rows.Next() {
		var i ControlRun
		if err := rows.Scan(
			&i.RunID,
			&i.ThreadID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.WorkflowKind,
			&i.Mode,
			&i.CurrentNode,
			&i.ParentRunID,
			&i.PlannerVersion,
			&i.AgentRole,
			&i.TraceGroupID,
			&i.CheckpointID,
			&i.CheckpointState,
			&i.BudgetState,
			&i.ResponseText,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForUser = `-- name: ListRunsForUser :many
SELECT run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata FROM control_runs
WHERE user_id = $1
  AND ($2::text = '' OR thread_id = $2)
  AND ($3::text = '' OR status = $3)
ORDER BY updated_at DESC
LIMIT $4 OFFSET $5
`

type ListRunsForUserParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListRunsForUser(ctx context.Context, arg ListRunsForUserParams) ([]ControlRun, error) {
	rows, err := q.db.Query(ctx, listRunsForUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRun
	for rows.Next() {
		var i ControlRun
		if err := rows.Scan(
			&i.RunID,
			&i.ThreadID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.WorkflowKind,
			&i.Mode,
			&i.CurrentNode,
			&i.ParentRunID,
			&i.PlannerVersion,
			&i.AgentRole,
			&i.TraceGroupID,
			&i.CheckpointID,
			&i.CheckpointState,
			&i.BudgetState,
			&i.ResponseText,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT message_id, thread_id, role, content, created_at, metadata, run_id FROM control_thread_messages WHERE thread_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListThreadMessages(ctx context.Context, threadID string) ([]ControlThreadMessage, error) {
	rows, err := q.db.Query(ctx, listThreadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlThreadMessage
	for rows.Next() {
		var i ControlThreadMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.Metadata,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessagesForUser = `-- name: ListThreadMessagesForUser :many
SELECT m.message_id, m.thread_id, m.role, m.content, m.created_at, m.metadata, m.run_id
FROM control_thread_messages m
JOIN control_threads t ON t.thread_id = m.thread_id
WHERE m.thread_id = $1
  AND t.user_id = $2
ORDER BY m.created_at ASC
`

type ListThreadMessagesForUserParams struct {
	ThreadID string `json:"thread_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) ListThreadMessagesForUser(ctx context.Context, arg ListThreadMessagesForUserParams) ([]ControlThreadMessage, error) {
	rows, err := q.db.Query(ctx, listThreadMessagesForUser, arg.ThreadID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlThreadMessage
	for rows.Next() {
		var i ControlThreadMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.Metadata,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata FROM control_threads
WHERE ($1::text = '' OR status = $1)
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListThreadsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListThreads(ctx context.Context, arg ListThreadsParams) ([]ControlThread, error) {
	rows, err := q.db.Query(ctx, listThreads, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlThread
	for rows.Next() {
		var i ControlThread
		if err := rows.Scan(
			&i.ThreadID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestRunID,
			&i.CheckpointID,
			&i.Summary,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForUser = `-- name: ListThreadsForUser :many
SELECT thread_id, user_id, title, status, created_at, updated_at, latest_run_id, checkpoint_id, summary, metadata FROM control_threads
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
ORDER BY updated_at DESC
LIMIT $3 OFFSET $4
`

type ListThreadsForUserParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListThreadsForUser(ctx context.Context, arg ListThreadsForUserParams) ([]ControlThread, error) {
	rows, err := q.db.Query(ctx, listThreadsForUser,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlThread
	for rows.Next() {
		var i ControlThread
		if err := rows.Scan(
			&i.ThreadID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestRunID,
			&i.CheckpointID,
			&i.Summary,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunEventSequence = `-- name: NextRunEventSequence :one
SELECT COALESCE(MAX(sequence_number), 0) + 1 AS next_sequence FROM control_run_events WHERE run_id = $1
`

func (q *Queries) NextRunEventSequence(ctx context.Context, runID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextRunEventSequence, runID)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const resourceStorageStats = `-- name: ResourceStorageStats :one
SELECT count(*)::bigint AS total_resources, COALESCE(sum(size_bytes), 0)::bigint AS total_bytes
FROM control_resources
WHERE status = 'active'
`

type ResourceStorageStatsRow struct {
	TotalResources int64 `json:"total_resources"`
	TotalBytes     int64 `json:"total_bytes"`
}

func (q *Queries) ResourceStorageStats(ctx context.Context) (ResourceStorageStatsRow, error) {
	row := q.db.QueryRow(ctx, resourceStorageStats)
	var i ResourceStorageStatsRow
	err := row.Scan(&i.TotalResources, &i.TotalBytes)
	return i, err
}

const restoreResourceForUser = `-- name: RestoreResourceForUser :one
UPDATE control_resources
SET status = 'active',
    deleted_at = NULL,
    retention_expires_at = NULL,
    updated_at = $4
WHERE resource_id = $1
  AND owner_user_id = $2
  AND (COALESCE(owner_org_id, '') = '' OR owner_org_id = $3)
RETURNING resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type, size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind, source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
`

type RestoreResourceForUserParams struct {
	ResourceID  string             `json:"resource_id"`
	OwnerUserID string             `json:"owner_user_id"`
	OwnerOrgID  pgtype.Text        `json:"owner_org_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RestoreResourceForUser(ctx context.Context, arg RestoreResourceForUserParams) (ControlResource, error) {
	row := q.db.QueryRow(ctx, restoreResourceForUser,
		arg.ResourceID,
		arg.OwnerUserID,
		arg.OwnerOrgID,
		arg.UpdatedAt,
	)
	var i ControlResource
	err := row.Scan(
		&i.ResourceID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.OwnerRole,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.StoragePath,
		&i.SourceType,
		&i.ResourceKind,
		&i.SourceUri,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RetentionExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const setThreadLatestRun = `-- name: SetThreadLatestRun :exec
UPDATE control_threads SET latest_run_id = $2, updated_at = $3 WHERE thread_id = $1
`

type SetThreadLatestRunParams struct {
	ThreadID    string             `json:"thread_id"`
	LatestRunID pgtype.Text        `json:"latest_run_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetThreadLatestRun(ctx context.Context, arg SetThreadLatestRunParams) error {
	_, err := q.db.Exec(ctx, setThreadLatestRun, arg.ThreadID, arg.LatestRunID, arg.UpdatedAt)
	return err
}

const softDeleteResourceForUser = `-- name: SoftDeleteResourceForUser :one
UPDATE control_resources
SET status = 'deleted',
    deleted_at = $4,
    retention_expires_at = $5,
    updated_at = $4
WHERE resource_id = $1
  AND owner_user_id = $2
  AND (COALESCE(owner_org_id, '') = '' OR owner_org_id = $3)
  AND status <> 'deleted'
RETURNING resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type, size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind, source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
`

type SoftDeleteResourceForUserParams struct {
	ResourceID         string             `json:"resource_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	RetentionExpiresAt pgtype.Timestamptz `json:"retention_expires_at"`
}

func (q *Queries) SoftDeleteResourceForUser(ctx context.Context, arg SoftDeleteResourceForUserParams) (ControlResource, error) {
	row := q.db.QueryRow(ctx, softDeleteResourceForUser,
		arg.ResourceID,
		arg.OwnerUserID,
		arg.OwnerOrgID,
		arg.DeletedAt,
		arg.RetentionExpiresAt,
	)
	var i ControlResource
	err := row.Scan(
		&i.ResourceID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.OwnerRole,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.StoragePath,
		&i.SourceType,
		&i.ResourceKind,
		&i.SourceUri,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RetentionExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE control_runs
SET status = $2,
    response_text = NULLIF($3, ''),
    error = NULLIF($4, ''),
    updated_at = $5,
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN $5 ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('succeeded', 'failed', 'canceled') THEN $5 ELSE completed_at END
WHERE run_id = $1
  AND status NOT IN ('succeeded', 'failed', 'canceled')
RETURNING run_id, thread_id, user_id, goal, status, workflow_kind, mode, current_node, parent_run_id, planner_version, agent_role, trace_group_id, checkpoint_id, checkpoint_state, budget_state, response_text, error, created_at, updated_at, started_at, completed_at, metadata
`

type UpdateRunStatusParams struct {
	RunID     string             `json:"run_id"`
	Status    string             `json:"status"`
	Column3   interface{}        `json:"column_3"`
	Column4   interface{}        `json:"column_4"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (ControlRun, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.RunID,
		arg.Status,
		arg.Column3,
		arg.Column4,
		arg.UpdatedAt,
	)
	var i ControlRun
	err := row.Scan(
		&i.RunID,
		&i.ThreadID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.WorkflowKind,
		&i.Mode,
		&i.CurrentNode,
		&i.ParentRunID,
		&i.PlannerVersion,
		&i.AgentRole,
		&i.TraceGroupID,
		&i.CheckpointID,
		&i.CheckpointState,
		&i.BudgetState,
		&i.ResponseText,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const upsertResource = `-- name: UpsertResource :one
INSERT INTO control_resources (
  resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type,
  size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind,
  source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
)
VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16, $17, $18, $19, $20
)
ON CONFLICT (resource_id) DO UPDATE SET
  owner_user_id = EXCLUDED.owner_user_id,
  owner_org_id = EXCLUDED.owner_org_id,
  owner_role = EXCLUDED.owner_role,
  original_name = EXCLUDED.original_name,
  content_type = EXCLUDED.content_type,
  size_bytes = EXCLUDED.size_bytes,
  sha256 = EXCLUDED.sha256,
  storage_uri = EXCLUDED.storage_uri,
  storage_path = EXCLUDED.storage_path,
  source_type = EXCLUDED.source_type,
  resource_kind = EXCLUDED.resource_kind,
  source_uri = EXCLUDED.source_uri,
  project_id = EXCLUDED.project_id,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  retention_expires_at = EXCLUDED.retention_expires_at,
  metadata = EXCLUDED.metadata
RETURNING resource_id, owner_user_id, owner_org_id, owner_role, original_name, content_type, size_bytes, sha256, storage_uri, storage_path, source_type, resource_kind, source_uri, project_id, status, created_at, updated_at, deleted_at, retention_expires_at, metadata
`

type UpsertResourceParams struct {
	ResourceID         string             `json:"resource_id"`
	OwnerUserID        string             `json:"owner_user_id"`
	OwnerOrgID         pgtype.Text        `json:"owner_org_id"`
	OwnerRole          pgtype.Text        `json:"owner_role"`
	OriginalName       string             `json:"original_name"`
	ContentType        pgtype.Text        `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	Sha256             pgtype.Text        `json:"sha256"`
	StorageUri         pgtype.Text        `json:"storage_uri"`
	StoragePath        pgtype.Text        `json:"storage_path"`
	SourceType         string             `json:"source_type"`
	ResourceKind       string             `json:"resource_kind"`
	SourceUri          pgtype.Text        `json:"source_uri"`
	ProjectID          pgtype.Text        `json:"project_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	RetentionExpiresAt pgtype.Timestamptz `json:"retention_expires_at"`
	Metadata           []byte             `json:"metadata"`
}

func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) (ControlResource, error) {
	row := q.db.QueryRow(ctx, upsertResource,
		arg.ResourceID,
		arg.OwnerUserID,
		arg.OwnerOrgID,
		arg.OwnerRole,
		arg.OriginalName,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.StorageUri,
		arg.StoragePath,
		arg.SourceType,
		arg.ResourceKind,
		arg.SourceUri,
		arg.ProjectID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.RetentionExpiresAt,
		arg.Metadata,
	)
	var i ControlResource
	err := row.Scan(
		&i.ResourceID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.OwnerRole,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageUri,
		&i.StoragePath,
		&i.SourceType,
		&i.ResourceKind,
		&i.SourceUri,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RetentionExpiresAt,
		&i.Metadata,
	)
	return i, err
}
