package httpapi

// Opt-in live end-to-end verification of the HDF5 viewer chain: drives the real Go
// router against a REAL running Python image service (python -m
// ultra_deepagents.image_service), using real h5py fixtures, over the exact URLs the
// frontend uses. Auto-skipped in CI. Fixtures are generated by any h5py script that
// writes fx1__volume.h5 (a /volume/ct int16 (40,64,80) volume, /volume/labels,
// /tables/measurements compound with 57 rows) and fx2__synthetic.dream3d (a plain
// HDF5 file: /DataContainers/<name>/CellData/... + _SIMPL_GEOMETRY). Run with:
//
//	ULTRA_HDF5_E2E_SIDECAR=http://127.0.0.1:18095 \
//	ULTRA_HDF5_E2E_FIXTURES=/path/to/uploads go test -run TestLiveHdf5EndToEnd ./internal/httpapi/
//
// Skipped unless both env vars are set.

import (
	"bytes"
	"encoding/json"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	"github.com/amilworks/bisque-ultra/backend/controlplane/internal/eventbus"
	"github.com/amilworks/bisque-ultra/backend/controlplane/internal/runcontrol"
	"github.com/amilworks/bisque-ultra/backend/controlplane/internal/store"
)

func TestLiveHdf5EndToEnd(t *testing.T) {
	sidecar := os.Getenv("ULTRA_HDF5_E2E_SIDECAR")
	fixtures := os.Getenv("ULTRA_HDF5_E2E_FIXTURES")
	if sidecar == "" || fixtures == "" {
		t.Skip("set ULTRA_HDF5_E2E_SIDECAR and ULTRA_HDF5_E2E_FIXTURES to run")
	}

	mem := store.NewMemoryStore()
	router := NewRouter(ServerDeps{
		Version:         "e2e",
		Runs:            runcontrol.NewService(mem, eventbus.NewMemoryBus()),
		Store:           mem,
		UploadRoot:      t.TempDir(),
		ImageServiceURL: sidecar,
	})

	upload := func(name, src string) string {
		t.Helper()
		data, err := os.ReadFile(filepath.Join(fixtures, src))
		if err != nil {
			t.Fatalf("read fixture: %v", err)
		}
		var body bytes.Buffer
		w := multipart.NewWriter(&body)
		part, _ := w.CreateFormFile("files", name)
		_, _ = part.Write(data)
		_ = w.Close()
		req := httptest.NewRequest(http.MethodPost, "/v2/uploads", &body)
		req.Header.Set("Content-Type", w.FormDataContentType())
		setProxyOwnerHeaders(req)
		rec := httptest.NewRecorder()
		router.ServeHTTP(rec, req)
		if rec.Code != http.StatusOK {
			t.Fatalf("upload %s: status=%d body=%s", name, rec.Code, rec.Body.String())
		}
		var resp struct {
			Uploaded []struct {
				FileID string `json:"file_id"`
			} `json:"uploaded"`
		}
		if err := json.Unmarshal(rec.Body.Bytes(), &resp); err != nil || len(resp.Uploaded) != 1 {
			t.Fatalf("upload %s: bad response %s", name, rec.Body.String())
		}
		return resp.Uploaded[0].FileID
	}
	get := func(path string) *httptest.ResponseRecorder {
		t.Helper()
		req := httptest.NewRequest(http.MethodGet, path, nil)
		setProxyOwnerHeaders(req)
		rec := httptest.NewRecorder()
		router.ServeHTTP(rec, req)
		return rec
	}

	h5ID := upload("volume.h5", "fx1__volume.h5")
	d3ID := upload("synthetic.dream3d", "fx2__synthetic.dream3d")

	// 1. The viewer gate: /v2/uploads/{id}/viewer must return kind:"hdf5" with the
	// embedded tree and the control-plane-injected file_id.
	rec := get("/v2/uploads/" + h5ID + "/viewer")
	if rec.Code != http.StatusOK {
		t.Fatalf("viewer: status=%d body=%s", rec.Code, rec.Body.String())
	}
	var viewer map[string]any
	if err := json.Unmarshal(rec.Body.Bytes(), &viewer); err != nil {
		t.Fatalf("viewer: %v", err)
	}
	if viewer["kind"] != "hdf5" {
		t.Fatalf("viewer kind = %v, want hdf5", viewer["kind"])
	}
	if viewer["file_id"] != h5ID {
		t.Fatalf("viewer file_id = %v, want %s", viewer["file_id"], h5ID)
	}
	hdf5Obj, _ := viewer["hdf5"].(map[string]any)
	if hdf5Obj == nil || hdf5Obj["supported"] != true {
		t.Fatalf("viewer hdf5 sub-object missing/unsupported: %v", viewer["hdf5"])
	}
	if _, ok := hdf5Obj["tree"].([]any); !ok {
		t.Fatalf("viewer hdf5.tree missing")
	}

	// 2. Dataset summary through the proxy: real file_id echoed by the sidecar.
	rec = get("/v2/uploads/" + h5ID + "/hdf5/dataset?dataset_path=" + url.QueryEscape("/volume/ct"))
	if rec.Code != http.StatusOK {
		t.Fatalf("dataset: status=%d body=%s", rec.Code, rec.Body.String())
	}
	var summary map[string]any
	_ = json.Unmarshal(rec.Body.Bytes(), &summary)
	if summary["file_id"] != h5ID {
		t.Fatalf("dataset file_id = %v, want %s (frontend builds preview URLs from it)", summary["file_id"], h5ID)
	}
	if summary["preview_kind"] != "scalar_volume" {
		t.Fatalf("dataset preview_kind = %v", summary["preview_kind"])
	}

	// 3. Slice + atlas PNGs.
	for _, u := range []string{
		"/v2/uploads/" + h5ID + "/hdf5/preview/slice?dataset_path=" + url.QueryEscape("/volume/ct") + "&axis=z&index=3",
		"/v2/uploads/" + h5ID + "/hdf5/preview/atlas?dataset_path=" + url.QueryEscape("/volume/labels"),
	} {
		rec = get(u)
		if rec.Code != http.StatusOK || !bytes.HasPrefix(rec.Body.Bytes(), []byte("\x89PNG\r\n\x1a\n")) {
			t.Fatalf("%s: status=%d, want 200 PNG", u, rec.Code)
		}
	}

	// 4. Scalar volume: x-volume-* headers forwarded, byte length coherent.
	rec = get("/v2/uploads/" + h5ID + "/hdf5/preview/scalar-volume?dataset_path=" + url.QueryEscape("/volume/ct"))
	if rec.Code != http.StatusOK {
		t.Fatalf("scalar-volume: status=%d", rec.Code)
	}
	w, _ := strconv.Atoi(rec.Header().Get("x-volume-width"))
	h, _ := strconv.Atoi(rec.Header().Get("x-volume-height"))
	d, _ := strconv.Atoi(rec.Header().Get("x-volume-depth"))
	bpv, _ := strconv.Atoi(rec.Header().Get("x-volume-bytes-per-voxel"))
	if w == 0 || h == 0 || d == 0 || rec.Body.Len() != w*h*d*bpv {
		t.Fatalf("scalar-volume: %dx%dx%d*%d != %d bytes", w, h, d, bpv, rec.Body.Len())
	}

	// 5. Histogram + table JSON.
	rec = get("/v2/uploads/" + h5ID + "/hdf5/preview/histogram?dataset_path=" + url.QueryEscape("/volume/ct") + "&bins=24")
	var hist struct {
		Bins   []any  `json:"bins"`
		FileID string `json:"file_id"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &hist); err != nil || rec.Code != http.StatusOK || len(hist.Bins) != 24 || hist.FileID != h5ID {
		t.Fatalf("histogram: status=%d bins=%d file_id=%q body=%.200s", rec.Code, len(hist.Bins), hist.FileID, rec.Body.String())
	}
	rec = get("/v2/uploads/" + h5ID + "/hdf5/preview/table?dataset_path=" + url.QueryEscape("/tables/measurements") + "&offset=0&limit=12")
	var table struct {
		Rows      []any `json:"rows"`
		TotalRows int   `json:"total_rows"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &table); err != nil || rec.Code != http.StatusOK || len(table.Rows) != 12 || table.TotalRows != 57 {
		t.Fatalf("table: status=%d rows=%d total=%d", rec.Code, len(table.Rows), table.TotalRows)
	}

	// 6. A .dream3d file is a plain HDF5 file: the generic viewer gate must still
	// open it as kind:"hdf5" with a walkable tree.
	rec = get("/v2/uploads/" + d3ID + "/viewer")
	if rec.Code != http.StatusOK {
		t.Fatalf("dream3d viewer: status=%d body=%s", rec.Code, rec.Body.String())
	}
	var d3viewer map[string]any
	if err := json.Unmarshal(rec.Body.Bytes(), &d3viewer); err != nil {
		t.Fatalf("dream3d viewer: %v", err)
	}
	if d3viewer["kind"] != "hdf5" || d3viewer["file_id"] != d3ID {
		t.Fatalf("dream3d viewer kind=%v file_id=%v, want hdf5/%s", d3viewer["kind"], d3viewer["file_id"], d3ID)
	}
	d3hdf5, _ := d3viewer["hdf5"].(map[string]any)
	if d3hdf5 == nil || d3hdf5["supported"] != true {
		t.Fatalf("dream3d viewer hdf5 sub-object missing/unsupported: %v", d3viewer["hdf5"])
	}
	if _, ok := d3hdf5["tree"].([]any); !ok {
		t.Fatalf("dream3d viewer hdf5.tree missing")
	}

	// 7. Unknown dataset -> 404 with a clean JSON error through the proxy.
	rec = get("/v2/uploads/" + h5ID + "/hdf5/dataset?dataset_path=" + url.QueryEscape("/nope"))
	var errResp struct {
		Error string `json:"error"`
	}
	if rec.Code != http.StatusNotFound || json.Unmarshal(rec.Body.Bytes(), &errResp) != nil || errResp.Error == "" {
		t.Fatalf("unknown dataset: status=%d body=%s", rec.Code, rec.Body.String())
	}
}
