// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// AuthSessionResponse defines model for AuthSessionResponse.
type AuthSessionResponse struct {
	Authenticated bool       `json:"authenticated"`
	User          JsonObject `json:"user"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
	Ts     string `json:"ts"`
}

// JsonObject defines model for JsonObject.
type JsonObject map[string]interface{}

// PublicConfigResponse defines model for PublicConfigResponse.
type PublicConfigResponse map[string]interface{}

// V2ArtifactListResponse defines model for V2ArtifactListResponse.
type V2ArtifactListResponse struct {
	Artifacts []V2ArtifactRecord `json:"artifacts"`
	Count     int                `json:"count"`
	RunId     string             `json:"run_id"`
}

// V2ArtifactRecord defines model for V2ArtifactRecord.
type V2ArtifactRecord struct {
	ArtifactId    string     `json:"artifact_id"`
	Category      *string    `json:"category,omitempty"`
	CreatedAt     string     `json:"created_at"`
	Kind          string     `json:"kind"`
	Metadata      JsonObject `json:"metadata"`
	MimeType      *string    `json:"mime_type,omitempty"`
	Path          *string    `json:"path,omitempty"`
	PreviewPath   *string    `json:"preview_path,omitempty"`
	ResultGroupId *string    `json:"result_group_id,omitempty"`
	RunId         string     `json:"run_id"`
	Sha256        *string    `json:"sha256,omitempty"`
	SizeBytes     *int64     `json:"size_bytes,omitempty"`
	SourcePath    *string    `json:"source_path,omitempty"`
	StorageUri    *string    `json:"storage_uri,omitempty"`
	ThreadId      *string    `json:"thread_id,omitempty"`
	Title         *string    `json:"title,omitempty"`
	ToolName      *string    `json:"tool_name,omitempty"`
	UpdatedAt     *string    `json:"updated_at,omitempty"`
}

// V2ArtifactResponse defines model for V2ArtifactResponse.
type V2ArtifactResponse struct {
	Artifact V2ArtifactRecord `json:"artifact"`
}

// V2GraphEventRecord defines model for V2GraphEventRecord.
type V2GraphEventRecord struct {
	AgentRole    *string    `json:"agent_role,omitempty"`
	CheckpointId *string    `json:"checkpoint_id,omitempty"`
	EventId      *string    `json:"event_id,omitempty"`
	EventKind    string     `json:"event_kind"`
	EventType    *string    `json:"event_type,omitempty"`
	Level        *string    `json:"level,omitempty"`
	Message      *string    `json:"message,omitempty"`
	NodeName     *string    `json:"node_name,omitempty"`
	Payload      JsonObject `json:"payload"`
	RunId        string     `json:"run_id"`
	ScopeId      *string    `json:"scope_id,omitempty"`
	TaskId       *string    `json:"task_id,omitempty"`
	ThreadId     *string    `json:"thread_id,omitempty"`
	Ts           *string    `json:"ts,omitempty"`
}

// V2RunBudget defines model for V2RunBudget.
type V2RunBudget struct {
	MaxRuntimeSeconds    *int                   `json:"max_runtime_seconds,omitempty"`
	MaxToolCalls         *int                   `json:"max_tool_calls,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// V2RunCancelRequest defines model for V2RunCancelRequest.
type V2RunCancelRequest struct {
	Metadata *JsonObject `json:"metadata,omitempty"`
	Reason   *string     `json:"reason,omitempty"`
}

// V2RunCreateRequest defines model for V2RunCreateRequest.
type V2RunCreateRequest struct {
	Benchmark         *JsonObject       `json:"benchmark,omitempty"`
	Budgets           *V2RunBudget      `json:"budgets,omitempty"`
	DatasetUris       *[]string         `json:"dataset_uris,omitempty"`
	FileIds           *[]string         `json:"file_ids,omitempty"`
	Goal              *string           `json:"goal,omitempty"`
	KnowledgeContext  *JsonObject       `json:"knowledge_context,omitempty"`
	Messages          []V2ThreadMessage `json:"messages"`
	Metadata          *JsonObject       `json:"metadata,omitempty"`
	ReasoningMode     *string           `json:"reasoning_mode,omitempty"`
	ResourceUris      *[]string         `json:"resource_uris,omitempty"`
	SelectedToolNames *[]string         `json:"selected_tool_names,omitempty"`
	SelectionContext  *JsonObject       `json:"selection_context,omitempty"`
	WorkflowHint      *JsonObject       `json:"workflow_hint,omitempty"`
}

// V2RunEventsResponse defines model for V2RunEventsResponse.
type V2RunEventsResponse struct {
	Count  int                  `json:"count"`
	Events []V2GraphEventRecord `json:"events"`
	RunId  string               `json:"run_id"`
}

// V2RunListResponse defines model for V2RunListResponse.
type V2RunListResponse struct {
	Count int           `json:"count"`
	Runs  []V2RunRecord `json:"runs"`
}

// V2RunRecord defines model for V2RunRecord.
type V2RunRecord struct {
	AgentRole       *string     `json:"agent_role,omitempty"`
	BudgetState     *JsonObject `json:"budget_state,omitempty"`
	CheckpointId    *string     `json:"checkpoint_id,omitempty"`
	CheckpointState *JsonObject `json:"checkpoint_state,omitempty"`
	CompletedAt     *string     `json:"completed_at,omitempty"`
	CreatedAt       string      `json:"created_at"`
	CurrentNode     *string     `json:"current_node,omitempty"`
	Error           *string     `json:"error,omitempty"`
	Goal            string      `json:"goal"`
	Metadata        JsonObject  `json:"metadata"`
	Mode            *string     `json:"mode,omitempty"`
	ParentRunId     *string     `json:"parent_run_id,omitempty"`
	PlannerVersion  *string     `json:"planner_version,omitempty"`
	ResponseText    *string     `json:"response_text,omitempty"`
	RunId           string      `json:"run_id"`
	StartedAt       *string     `json:"started_at,omitempty"`
	Status          string      `json:"status"`
	ThreadId        *string     `json:"thread_id,omitempty"`
	TraceGroupId    *string     `json:"trace_group_id,omitempty"`
	UpdatedAt       string      `json:"updated_at"`
	UserId          *string     `json:"user_id,omitempty"`
	WorkflowKind    string      `json:"workflow_kind"`
}

// V2RunResumeRequest defines model for V2RunResumeRequest.
type V2RunResumeRequest struct {
	Decision *string     `json:"decision,omitempty"`
	Metadata *JsonObject `json:"metadata,omitempty"`
	Note     *string     `json:"note,omitempty"`
}

// V2ThreadCreateRequest defines model for V2ThreadCreateRequest.
type V2ThreadCreateRequest struct {
	ConversationId  *string            `json:"conversation_id,omitempty"`
	InitialMessages *[]V2ThreadMessage `json:"initial_messages,omitempty"`
	Metadata        *JsonObject        `json:"metadata,omitempty"`
	Title           *string            `json:"title,omitempty"`
}

// V2ThreadListResponse defines model for V2ThreadListResponse.
type V2ThreadListResponse struct {
	Count   int              `json:"count"`
	Threads []V2ThreadRecord `json:"threads"`
}

// V2ThreadMessage defines model for V2ThreadMessage.
type V2ThreadMessage struct {
	Content   string      `json:"content"`
	CreatedAt *string     `json:"created_at,omitempty"`
	MessageId *string     `json:"message_id,omitempty"`
	Metadata  *JsonObject `json:"metadata,omitempty"`
	Role      string      `json:"role"`
	RunId     *string     `json:"run_id,omitempty"`
	ThreadId  *string     `json:"thread_id,omitempty"`
}

// V2ThreadMessageListResponse defines model for V2ThreadMessageListResponse.
type V2ThreadMessageListResponse struct {
	Count    int               `json:"count"`
	Messages []V2ThreadMessage `json:"messages"`
	ThreadId string            `json:"thread_id"`
}

// V2ThreadRecord defines model for V2ThreadRecord.
type V2ThreadRecord struct {
	CheckpointId *string    `json:"checkpoint_id,omitempty"`
	CreatedAt    string     `json:"created_at"`
	LatestRunId  *string    `json:"latest_run_id,omitempty"`
	Metadata     JsonObject `json:"metadata"`
	Status       string     `json:"status"`
	Summary      *string    `json:"summary,omitempty"`
	ThreadId     string     `json:"thread_id"`
	Title        *string    `json:"title,omitempty"`
	UpdatedAt    string     `json:"updated_at"`
	UserId       *string    `json:"user_id,omitempty"`
}

// V2ThreadUpsertRequest defines model for V2ThreadUpsertRequest.
type V2ThreadUpsertRequest struct {
	Messages *[]V2ThreadMessage `json:"messages,omitempty"`
	Metadata *JsonObject        `json:"metadata,omitempty"`
	Title    *string            `json:"title,omitempty"`
}

// RunID defines model for RunID.
type RunID = string

// ThreadID defines model for ThreadID.
type ThreadID = string

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	ThreadId *string `form:"thread_id,omitempty" json:"thread_id,omitempty"`
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRunArtifactsParams defines parameters for ListRunArtifacts.
type ListRunArtifactsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRunEventsParams defines parameters for ListRunEvents.
type ListRunEventsParams struct {
	Limit  *int  `form:"limit,omitempty" json:"limit,omitempty"`
	Stream *bool `form:"stream,omitempty" json:"stream,omitempty"`
}

// ListThreadsParams defines parameters for ListThreads.
type ListThreadsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// CancelRunJSONRequestBody defines body for CancelRun for application/json ContentType.
type CancelRunJSONRequestBody = V2RunCancelRequest

// ResumeRunJSONRequestBody defines body for ResumeRun for application/json ContentType.
type ResumeRunJSONRequestBody = V2RunResumeRequest

// CreateThreadJSONRequestBody defines body for CreateThread for application/json ContentType.
type CreateThreadJSONRequestBody = V2ThreadCreateRequest

// UpsertThreadJSONRequestBody defines body for UpsertThread for application/json ContentType.
type UpsertThreadJSONRequestBody = V2ThreadUpsertRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = V2RunCreateRequest

// Getter for additional properties for V2RunBudget. Returns the specified
// element and whether it was found
func (a V2RunBudget) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for V2RunBudget
func (a *V2RunBudget) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for V2RunBudget to handle AdditionalProperties
func (a *V2RunBudget) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max_runtime_seconds"]; found {
		err = json.Unmarshal(raw, &a.MaxRuntimeSeconds)
		if err != nil {
			return fmt.Errorf("error reading 'max_runtime_seconds': %w", err)
		}
		delete(object, "max_runtime_seconds")
	}

	if raw, found := object["max_tool_calls"]; found {
		err = json.Unmarshal(raw, &a.MaxToolCalls)
		if err != nil {
			return fmt.Errorf("error reading 'max_tool_calls': %w", err)
		}
		delete(object, "max_tool_calls")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for V2RunBudget to handle AdditionalProperties
func (a V2RunBudget) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MaxRuntimeSeconds != nil {
		object["max_runtime_seconds"], err = json.Marshal(a.MaxRuntimeSeconds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'max_runtime_seconds': %w", err)
		}
	}

	if a.MaxToolCalls != nil {
		object["max_tool_calls"], err = json.Marshal(a.MaxToolCalls)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'max_tool_calls': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/auth/session)
	GetAuthSession(w http.ResponseWriter, r *http.Request)

	// (GET /v1/config/public)
	GetPublicConfig(w http.ResponseWriter, r *http.Request)

	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /v2/artifacts/{artifact_id})
	GetArtifact(w http.ResponseWriter, r *http.Request, artifactId string)

	// (GET /v2/runs)
	ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams)

	// (GET /v2/runs/{run_id})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (GET /v2/runs/{run_id}/artifacts)
	ListRunArtifacts(w http.ResponseWriter, r *http.Request, runId RunID, params ListRunArtifactsParams)

	// (POST /v2/runs/{run_id}/cancel)
	CancelRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (GET /v2/runs/{run_id}/events)
	ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunID, params ListRunEventsParams)

	// (POST /v2/runs/{run_id}/resume)
	ResumeRun(w http.ResponseWriter, r *http.Request, runId RunID)

	// (GET /v2/threads)
	ListThreads(w http.ResponseWriter, r *http.Request, params ListThreadsParams)

	// (POST /v2/threads)
	CreateThread(w http.ResponseWriter, r *http.Request)

	// (GET /v2/threads/{thread_id})
	GetThread(w http.ResponseWriter, r *http.Request, threadId ThreadID)

	// (PUT /v2/threads/{thread_id})
	UpsertThread(w http.ResponseWriter, r *http.Request, threadId ThreadID)

	// (GET /v2/threads/{thread_id}/messages)
	ListThreadMessages(w http.ResponseWriter, r *http.Request, threadId ThreadID)

	// (POST /v2/threads/{thread_id}/runs)
	CreateRun(w http.ResponseWriter, r *http.Request, threadId ThreadID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /v1/auth/session)
func (_ Unimplemented) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/config/public)
func (_ Unimplemented) GetPublicConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/artifacts/{artifact_id})
func (_ Unimplemented) GetArtifact(w http.ResponseWriter, r *http.Request, artifactId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/runs)
func (_ Unimplemented) ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/runs/{run_id})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/runs/{run_id}/artifacts)
func (_ Unimplemented) ListRunArtifacts(w http.ResponseWriter, r *http.Request, runId RunID, params ListRunArtifactsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v2/runs/{run_id}/cancel)
func (_ Unimplemented) CancelRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/runs/{run_id}/events)
func (_ Unimplemented) ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunID, params ListRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v2/runs/{run_id}/resume)
func (_ Unimplemented) ResumeRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/threads)
func (_ Unimplemented) ListThreads(w http.ResponseWriter, r *http.Request, params ListThreadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v2/threads)
func (_ Unimplemented) CreateThread(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/threads/{thread_id})
func (_ Unimplemented) GetThread(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /v2/threads/{thread_id})
func (_ Unimplemented) UpsertThread(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v2/threads/{thread_id}/messages)
func (_ Unimplemented) ListThreadMessages(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v2/threads/{thread_id}/runs)
func (_ Unimplemented) CreateRun(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAuthSession operation middleware
func (siw *ServerInterfaceWrapper) GetAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicConfig operation middleware
func (siw *ServerInterfaceWrapper) GetPublicConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtifact operation middleware
func (siw *ServerInterfaceWrapper) GetArtifact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artifact_id" -------------
	var artifactId string

	err = runtime.BindStyledParameterWithOptions("simple", "artifact_id", chi.URLParam(r, "artifact_id"), &artifactId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifact_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtifact(w, r, artifactId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRuns operation middleware
func (siw *ServerInterfaceWrapper) ListRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsParams

	// ------------- Optional query parameter "thread_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "thread_id", r.URL.Query(), &params.ThreadId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "thread_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "thread_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunArtifacts operation middleware
func (siw *ServerInterfaceWrapper) ListRunArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunArtifactsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunArtifacts(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelRun operation middleware
func (siw *ServerInterfaceWrapper) CancelRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunEvents operation middleware
func (siw *ServerInterfaceWrapper) ListRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "stream" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "stream", r.URL.Query(), &params.Stream, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "stream"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stream", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeRun operation middleware
func (siw *ServerInterfaceWrapper) ResumeRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunID

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListThreads operation middleware
func (siw *ServerInterfaceWrapper) ListThreads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListThreadsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListThreads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateThread operation middleware
func (siw *ServerInterfaceWrapper) CreateThread(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateThread(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetThread operation middleware
func (siw *ServerInterfaceWrapper) GetThread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "thread_id" -------------
	var threadId ThreadID

	err = runtime.BindStyledParameterWithOptions("simple", "thread_id", chi.URLParam(r, "thread_id"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "thread_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetThread(w, r, threadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpsertThread operation middleware
func (siw *ServerInterfaceWrapper) UpsertThread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "thread_id" -------------
	var threadId ThreadID

	err = runtime.BindStyledParameterWithOptions("simple", "thread_id", chi.URLParam(r, "thread_id"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "thread_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpsertThread(w, r, threadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListThreadMessages operation middleware
func (siw *ServerInterfaceWrapper) ListThreadMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "thread_id" -------------
	var threadId ThreadID

	err = runtime.BindStyledParameterWithOptions("simple", "thread_id", chi.URLParam(r, "thread_id"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "thread_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListThreadMessages(w, r, threadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "thread_id" -------------
	var threadId ThreadID

	err = runtime.BindStyledParameterWithOptions("simple", "thread_id", chi.URLParam(r, "thread_id"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "thread_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, threadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/session", wrapper.GetAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/config/public", wrapper.GetPublicConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/artifacts/{artifact_id}", wrapper.GetArtifact)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/runs", wrapper.ListRuns)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/runs/{run_id}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/runs/{run_id}/artifacts", wrapper.ListRunArtifacts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v2/runs/{run_id}/cancel", wrapper.CancelRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/runs/{run_id}/events", wrapper.ListRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v2/runs/{run_id}/resume", wrapper.ResumeRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/threads", wrapper.ListThreads)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v2/threads", wrapper.CreateThread)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/threads/{thread_id}", wrapper.GetThread)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v2/threads/{thread_id}", wrapper.UpsertThread)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v2/threads/{thread_id}/messages", wrapper.ListThreadMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v2/threads/{thread_id}/runs", wrapper.CreateRun)
	})

	return r
}

type GetAuthSessionRequestObject struct {
}

type GetAuthSessionResponseObject interface {
	VisitGetAuthSessionResponse(w http.ResponseWriter) error
}

type GetAuthSession200JSONResponse AuthSessionResponse

func (response GetAuthSession200JSONResponse) VisitGetAuthSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicConfigRequestObject struct {
}

type GetPublicConfigResponseObject interface {
	VisitGetPublicConfigResponse(w http.ResponseWriter) error
}

type GetPublicConfig200JSONResponse PublicConfigResponse

func (response GetPublicConfig200JSONResponse) VisitGetPublicConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetArtifactRequestObject struct {
	ArtifactId string `json:"artifact_id"`
}

type GetArtifactResponseObject interface {
	VisitGetArtifactResponse(w http.ResponseWriter) error
}

type GetArtifact200JSONResponse V2ArtifactResponse

func (response GetArtifact200JSONResponse) VisitGetArtifactResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunsRequestObject struct {
	Params ListRunsParams
}

type ListRunsResponseObject interface {
	VisitListRunsResponse(w http.ResponseWriter) error
}

type ListRuns200JSONResponse V2RunListResponse

func (response ListRuns200JSONResponse) VisitListRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRunRequestObject struct {
	RunId RunID `json:"run_id"`
}

type GetRunResponseObject interface {
	VisitGetRunResponse(w http.ResponseWriter) error
}

type GetRun200JSONResponse V2RunRecord

func (response GetRun200JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunArtifactsRequestObject struct {
	RunId  RunID `json:"run_id"`
	Params ListRunArtifactsParams
}

type ListRunArtifactsResponseObject interface {
	VisitListRunArtifactsResponse(w http.ResponseWriter) error
}

type ListRunArtifacts200JSONResponse V2ArtifactListResponse

func (response ListRunArtifacts200JSONResponse) VisitListRunArtifactsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelRunRequestObject struct {
	RunId RunID `json:"run_id"`
	Body  *CancelRunJSONRequestBody
}

type CancelRunResponseObject interface {
	VisitCancelRunResponse(w http.ResponseWriter) error
}

type CancelRun200JSONResponse V2RunRecord

func (response CancelRun200JSONResponse) VisitCancelRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunEventsRequestObject struct {
	RunId  RunID `json:"run_id"`
	Params ListRunEventsParams
}

type ListRunEventsResponseObject interface {
	VisitListRunEventsResponse(w http.ResponseWriter) error
}

type ListRunEvents200JSONResponse V2RunEventsResponse

func (response ListRunEvents200JSONResponse) VisitListRunEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunEvents200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ListRunEvents200TexteventStreamResponse) VisitListRunEventsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type ResumeRunRequestObject struct {
	RunId RunID `json:"run_id"`
	Body  *ResumeRunJSONRequestBody
}

type ResumeRunResponseObject interface {
	VisitResumeRunResponse(w http.ResponseWriter) error
}

type ResumeRun200JSONResponse V2RunRecord

func (response ResumeRun200JSONResponse) VisitResumeRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListThreadsRequestObject struct {
	Params ListThreadsParams
}

type ListThreadsResponseObject interface {
	VisitListThreadsResponse(w http.ResponseWriter) error
}

type ListThreads200JSONResponse V2ThreadListResponse

func (response ListThreads200JSONResponse) VisitListThreadsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateThreadRequestObject struct {
	Body *CreateThreadJSONRequestBody
}

type CreateThreadResponseObject interface {
	VisitCreateThreadResponse(w http.ResponseWriter) error
}

type CreateThread200JSONResponse V2ThreadRecord

func (response CreateThread200JSONResponse) VisitCreateThreadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetThreadRequestObject struct {
	ThreadId ThreadID `json:"thread_id"`
}

type GetThreadResponseObject interface {
	VisitGetThreadResponse(w http.ResponseWriter) error
}

type GetThread200JSONResponse V2ThreadRecord

func (response GetThread200JSONResponse) VisitGetThreadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertThreadRequestObject struct {
	ThreadId ThreadID `json:"thread_id"`
	Body     *UpsertThreadJSONRequestBody
}

type UpsertThreadResponseObject interface {
	VisitUpsertThreadResponse(w http.ResponseWriter) error
}

type UpsertThread200JSONResponse V2ThreadRecord

func (response UpsertThread200JSONResponse) VisitUpsertThreadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListThreadMessagesRequestObject struct {
	ThreadId ThreadID `json:"thread_id"`
}

type ListThreadMessagesResponseObject interface {
	VisitListThreadMessagesResponse(w http.ResponseWriter) error
}

type ListThreadMessages200JSONResponse V2ThreadMessageListResponse

func (response ListThreadMessages200JSONResponse) VisitListThreadMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRunRequestObject struct {
	ThreadId ThreadID `json:"thread_id"`
	Body     *CreateRunJSONRequestBody
}

type CreateRunResponseObject interface {
	VisitCreateRunResponse(w http.ResponseWriter) error
}

type CreateRun200JSONResponse V2RunRecord

func (response CreateRun200JSONResponse) VisitCreateRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRun200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateRun200TexteventStreamResponse) VisitCreateRunResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /v1/auth/session)
	GetAuthSession(ctx context.Context, request GetAuthSessionRequestObject) (GetAuthSessionResponseObject, error)

	// (GET /v1/config/public)
	GetPublicConfig(ctx context.Context, request GetPublicConfigRequestObject) (GetPublicConfigResponseObject, error)

	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)

	// (GET /v2/artifacts/{artifact_id})
	GetArtifact(ctx context.Context, request GetArtifactRequestObject) (GetArtifactResponseObject, error)

	// (GET /v2/runs)
	ListRuns(ctx context.Context, request ListRunsRequestObject) (ListRunsResponseObject, error)

	// (GET /v2/runs/{run_id})
	GetRun(ctx context.Context, request GetRunRequestObject) (GetRunResponseObject, error)

	// (GET /v2/runs/{run_id}/artifacts)
	ListRunArtifacts(ctx context.Context, request ListRunArtifactsRequestObject) (ListRunArtifactsResponseObject, error)

	// (POST /v2/runs/{run_id}/cancel)
	CancelRun(ctx context.Context, request CancelRunRequestObject) (CancelRunResponseObject, error)

	// (GET /v2/runs/{run_id}/events)
	ListRunEvents(ctx context.Context, request ListRunEventsRequestObject) (ListRunEventsResponseObject, error)

	// (POST /v2/runs/{run_id}/resume)
	ResumeRun(ctx context.Context, request ResumeRunRequestObject) (ResumeRunResponseObject, error)

	// (GET /v2/threads)
	ListThreads(ctx context.Context, request ListThreadsRequestObject) (ListThreadsResponseObject, error)

	// (POST /v2/threads)
	CreateThread(ctx context.Context, request CreateThreadRequestObject) (CreateThreadResponseObject, error)

	// (GET /v2/threads/{thread_id})
	GetThread(ctx context.Context, request GetThreadRequestObject) (GetThreadResponseObject, error)

	// (PUT /v2/threads/{thread_id})
	UpsertThread(ctx context.Context, request UpsertThreadRequestObject) (UpsertThreadResponseObject, error)

	// (GET /v2/threads/{thread_id}/messages)
	ListThreadMessages(ctx context.Context, request ListThreadMessagesRequestObject) (ListThreadMessagesResponseObject, error)

	// (POST /v2/threads/{thread_id}/runs)
	CreateRun(ctx context.Context, request CreateRunRequestObject) (CreateRunResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAuthSession operation middleware
func (sh *strictHandler) GetAuthSession(w http.ResponseWriter, r *http.Request) {
	var request GetAuthSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthSession(ctx, request.(GetAuthSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthSessionResponseObject); ok {
		if err := validResponse.VisitGetAuthSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicConfig operation middleware
func (sh *strictHandler) GetPublicConfig(w http.ResponseWriter, r *http.Request) {
	var request GetPublicConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicConfig(ctx, request.(GetPublicConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicConfigResponseObject); ok {
		if err := validResponse.VisitGetPublicConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArtifact operation middleware
func (sh *strictHandler) GetArtifact(w http.ResponseWriter, r *http.Request, artifactId string) {
	var request GetArtifactRequestObject

	request.ArtifactId = artifactId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtifact(ctx, request.(GetArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtifactResponseObject); ok {
		if err := validResponse.VisitGetArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRuns operation middleware
func (sh *strictHandler) ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams) {
	var request ListRunsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRuns(ctx, request.(ListRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRuns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRunsResponseObject); ok {
		if err := validResponse.VisitListRunsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRun operation middleware
func (sh *strictHandler) GetRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request GetRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRun(ctx, request.(GetRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRunResponseObject); ok {
		if err := validResponse.VisitGetRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRunArtifacts operation middleware
func (sh *strictHandler) ListRunArtifacts(w http.ResponseWriter, r *http.Request, runId RunID, params ListRunArtifactsParams) {
	var request ListRunArtifactsRequestObject

	request.RunId = runId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRunArtifacts(ctx, request.(ListRunArtifactsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRunArtifacts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRunArtifactsResponseObject); ok {
		if err := validResponse.VisitListRunArtifactsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelRun operation middleware
func (sh *strictHandler) CancelRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request CancelRunRequestObject

	request.RunId = runId

	var body CancelRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelRun(ctx, request.(CancelRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelRunResponseObject); ok {
		if err := validResponse.VisitCancelRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRunEvents operation middleware
func (sh *strictHandler) ListRunEvents(w http.ResponseWriter, r *http.Request, runId RunID, params ListRunEventsParams) {
	var request ListRunEventsRequestObject

	request.RunId = runId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRunEvents(ctx, request.(ListRunEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRunEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRunEventsResponseObject); ok {
		if err := validResponse.VisitListRunEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeRun operation middleware
func (sh *strictHandler) ResumeRun(w http.ResponseWriter, r *http.Request, runId RunID) {
	var request ResumeRunRequestObject

	request.RunId = runId

	var body ResumeRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeRun(ctx, request.(ResumeRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeRunResponseObject); ok {
		if err := validResponse.VisitResumeRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListThreads operation middleware
func (sh *strictHandler) ListThreads(w http.ResponseWriter, r *http.Request, params ListThreadsParams) {
	var request ListThreadsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListThreads(ctx, request.(ListThreadsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListThreads")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListThreadsResponseObject); ok {
		if err := validResponse.VisitListThreadsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateThread operation middleware
func (sh *strictHandler) CreateThread(w http.ResponseWriter, r *http.Request) {
	var request CreateThreadRequestObject

	var body CreateThreadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateThread(ctx, request.(CreateThreadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateThread")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateThreadResponseObject); ok {
		if err := validResponse.VisitCreateThreadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetThread operation middleware
func (sh *strictHandler) GetThread(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	var request GetThreadRequestObject

	request.ThreadId = threadId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetThread(ctx, request.(GetThreadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetThread")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetThreadResponseObject); ok {
		if err := validResponse.VisitGetThreadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpsertThread operation middleware
func (sh *strictHandler) UpsertThread(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	var request UpsertThreadRequestObject

	request.ThreadId = threadId

	var body UpsertThreadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpsertThread(ctx, request.(UpsertThreadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpsertThread")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpsertThreadResponseObject); ok {
		if err := validResponse.VisitUpsertThreadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListThreadMessages operation middleware
func (sh *strictHandler) ListThreadMessages(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	var request ListThreadMessagesRequestObject

	request.ThreadId = threadId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListThreadMessages(ctx, request.(ListThreadMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListThreadMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListThreadMessagesResponseObject); ok {
		if err := validResponse.VisitListThreadMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRun operation middleware
func (sh *strictHandler) CreateRun(w http.ResponseWriter, r *http.Request, threadId ThreadID) {
	var request CreateRunRequestObject

	request.ThreadId = threadId

	var body CreateRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRun(ctx, request.(CreateRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRunResponseObject); ok {
		if err := validResponse.VisitCreateRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpbc9u2Ev4rGpzzyGPKzkke9JaknTSdZpqqSV8yHg5MriTEIMDgYsf16L93AFC8SAAF0pbjvlnmAtjL",
	"txfs4h7lvKw4A6YkWtyjCgtcggJhfy01e/+T+YMwtEAVVhuUIIZLQAskNMtIgRIk4JsmAgq0UEJDgmS+",
	"gRKbVequMpRSCcLWaLtN0KeNAFwE91T289htt7uPlufXWm3+BCkJZ0uQFWcSrGCCVyAUAUuEtdoAUyTH",
	"ypzQ7HnFOQXM0DZBWoIwX/4rYIUW6D9pq6i0Pi79VXL2+9VXyJWVrmX5y94J9XaXye4gXq9K0C+AqdqE",
	"WZUKKy09cidISb+Wu3zUyy2x7/iOCEYvRUEU4QzTjx0mnAEOln7UV5TkbzlbkXWX/1Gb/HXxWiiywrn6",
	"jUg1YLGayv4gCkp5zDjtzkvIuSisxtzxWAh8Z37nXDPVUSJhCtYgzKca30cV3PiB2yvpcHo5KG/NVVBS",
	"/+kJMohac3FnPjJNKb6isKfeDrEAA8AMK+9e14T5DylB4QIrPMYDElSSEjK3VwRv1vejCAXcELjNohcI",
	"kJqqbC24rmo1Hl8TsneC5AZfvHwVtYskf0N2daecKVdclEbzBlev/m/inH99B3aSa5FDvKhScYHXkGlB",
	"oujbEBtFTRSNM6binGYujEdQ66rowPII+X5k7fhH0rqfhXIP8B0UH/PEY1FnfKwJMB3g5J3A1ebnG2Dh",
	"qLAGpjLBI82RbyC/rjhhKtbUYE4fRxyMHu5zdCCgcAM0irIEKfE6blfGC4hHZIXvKMfFuHg3FDNyXkG0",
	"m2F5HU07zoHleAdrXKpj5VZBfgAvNXujizUcrSL6qC7x90xopkzekJBzVgzx2wmTZqENOTmmNGrNNsT3",
	"W8xyoEv4pkGqQ8eblgkFYMlZnO4DbNlAFmTrCli+KbG4HsfXlTVSRO3UGnSbICO/BGWSTL/+OsTbXoG1",
	"ItR4wchVa47j4sE147cUijVkOWcKvquR9YoLJ2NqSneD+VDHIQ/vD8ELYeus5AXEFjmuVhhvFQkUcpMl",
	"m6w9aQPC2TS933JxvaL8NtsQph5wyWrsFwxKNqfKcIIfuADY6DcGGgdJ3KO4ybeKmpugoMO3p+F7zhgh",
	"l5qFpNsTYce5PSDI9yPVOy6uZea2C+OwOL5S6qyYch4vKwrRxe/RK1yuhTCqYrFxA4TgIopyF4Yf63YY",
	"y2GFrUStrxxfQTFjILIbEJJE5V0bP623ZLv49aArosJihE2Hmjrj6juBcxh30e3fvQ4/SxCxWzVxPHAT",
	"CAU1C6yk7U3199m7xHX4PXqjswFF6jJcNxWQk2iITMM54womV36uvjhS/OWcGaRjm4EjbUUYUQTT7PnU",
	"PLHNhSFFTU57zs3Ga2Fk8tsdczkgw4f2UntgZgUsEPZ7WSH24hwLlolFbJ2tBwLno15v98OLOT5ptBah",
	"8snoOYUT9SQflrQ7J9kh7Ugt3EPvoajji6DhqoRiBXJUCp8GuYFEKnVZ4sg2+ZDux3RBHy23Dhi8yZqT",
	"s6TDwudKglADfY9/f57Y2ry34tYYbhf0hsg/NMw+UyXw7C1nSnA6+0gxM7GjqR/R/Oz8bG5O5xUwXBG0",
	"QC/O5mcvkJtbWG2kN+cp1mqTSjdvNP+rW2BGkzY9vy/QAr0D1RlLorb2tNtczOd70R5XFSW5XZ9+rftI",
	"7fxzSHO+6adVQwEyF6RSTjpDNttxvbUERpjczvLSyg72hqTpjv5OKY53xOiRx9HNHP8dgTZ2uDokiRu/",
	"nlKGvQGvh3tHMRMdEsv/RdrMEtP7zthjOwi03aQh6Q3zv3gH7nuzlOiR++UJ9eWZy/gQvBOzVdauk+HV",
	"jE31hsCvlm8axJ3/IcLAewb/4iZAj15JSUlUb2EBK6ypQovz+dx2vUmpS7R4aX8R5n6d+7rd/hP4aiUh",
	"cER3y7lny9Mafb+H5bH5UrMZJXLf5um9KzMG3WKp2aHpfRy1JKl7/nJ6uZuZoU/ikLBp70XEEOZfN4QT",
	"FTAerS97aD2fH4Xr0wSUGIC1ag0pPrcDI1sxcelRez1QeiDgbFn2hhd3j4u1/rTLifij0O14gWImBmDe",
	"tuGHMO76/M8Y4MFcIQCX/jNWmMq2ym2epp0+Hu0NTWxhDd+VM8X/apZ7W3qe5B16lrPkjAv316zeKGR4",
	"YRt5YTerG33P0836Xcht/z5nqqsf6HaOt32v6zTEgo72qaaJqqGedzEzvXY7rft52poeEzqqphhKQpnI",
	"dggcMToV2n0d6ycHfL8560k1rlcycyg/hH1635T8g2Vko8txEad59/wk6Amr4VMjfoIq7RHRNYUeR8rT",
	"ga3funp2YHPsRaIt7TbajkTeDzvS540/X3c9HMQa+YfVtLvdD0W6KcXAE4D24DXXD60HHl7M7YKp0MxU",
	"c506brv9JwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
