DROP TABLE IF EXISTS control_artifacts;
DROP TABLE IF EXISTS control_worker_heartbeats;
DROP TABLE IF EXISTS control_run_leases;
DROP TABLE IF EXISTS control_run_events;
DROP TABLE IF EXISTS control_runs;
DROP TABLE IF EXISTS control_thread_messages;
DROP TABLE IF EXISTS control_threads;
DROP TABLE IF EXISTS control_users;
DROP TABLE IF EXISTS control_organizations;
